import type { DragBlankQuestion } from '../../../types'
import {
  playwrightAssertionsReference,
  playwrightConfigurationReference,
  playwrightFixturesReference,
  playwrightLocatorsReference,
  playwrightProjectsReference,
  playwrightWritingTestsReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'playwright.drag-test-declaration',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Declare a Playwright test named opens settings.',
    instruction: 'Choose the function that defines an individual test.',
    template: { before: '', after: "('opens settings', async ({ page }) => {\n  // steps\n})" },
    options: [
      { id: 'test', label: 'test', code: 'test' },
      { id: 'expect', label: 'expect', code: 'expect' },
      { id: 'describe', label: 'describe', code: 'describe' },
      { id: 'page', label: 'page', code: 'page' },
    ],
    correctOptionId: 'test',
    explanation:
      'The test function declares one scenario using a title and an asynchronous callback that receives requested fixtures.',
    reference: playwrightWritingTestsReference,
  },
  {
    id: 'playwright.drag-await-click',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Wait for the Save button click to complete before continuing.',
    instruction: 'Choose the missing JavaScript keyword.',
    template: { before: '', after: " page.getByRole('button', { name: 'Save' }).click()" },
    options: [
      { id: 'await', label: 'await', code: 'await' },
      { id: 'async', label: 'async', code: 'async' },
      { id: 'return', label: 'return', code: 'return' },
      { id: 'yield', label: 'yield', code: 'yield' },
    ],
    correctOptionId: 'await',
    explanation:
      'Locator actions return promises, so await ensures the click and its actionability checks finish before the next step.',
    reference: playwrightWritingTestsReference,
  },
  {
    id: 'playwright.drag-label-locator',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Locate the email field by its associated label.',
    instruction: 'Choose the locator method that uses label text.',
    template: { before: 'page.', after: "('Email')" },
    options: [
      { id: 'label', label: 'getByLabel', code: 'getByLabel' },
      { id: 'role', label: 'getByRole', code: 'getByRole' },
      { id: 'title', label: 'getByTitle', code: 'getByTitle' },
      { id: 'test-id', label: 'getByTestId', code: 'getByTestId' },
    ],
    correctOptionId: 'label',
    explanation:
      'getByLabel connects the locator to the form control whose accessible label matches the supplied text.',
    reference: playwrightLocatorsReference,
  },
  {
    id: 'playwright.drag-filter-list',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Narrow the list items to the one containing Product 2.',
    instruction: 'Choose the Locator method that narrows an existing locator.',
    template: { before: "page.getByRole('listitem').", after: "({ hasText: 'Product 2' })" },
    options: [
      { id: 'filter', label: 'filter', code: 'filter' },
      { id: 'fill', label: 'fill', code: 'fill' },
      { id: 'focus', label: 'focus', code: 'focus' },
      { id: 'first', label: 'first', code: 'first' },
    ],
    correctOptionId: 'filter',
    explanation:
      'locator.filter narrows the current matches using conditions such as contained text or another locator.',
    reference: playwrightLocatorsReference,
  },
  {
    id: 'playwright.drag-text-assertion',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Assert that the status eventually has the exact text Saved.',
    instruction: 'Choose the web-first text matcher.',
    template: { before: "await expect(page.getByTestId('status')).", after: "('Saved')" },
    options: [
      { id: 'have-text', label: 'toHaveText', code: 'toHaveText' },
      { id: 'be-text', label: 'toBeText', code: 'toBeText' },
      { id: 'equal-text', label: 'toEqualText', code: 'toEqualText' },
      { id: 'read-text', label: 'readText', code: 'readText' },
    ],
    correctOptionId: 'have-text',
    explanation:
      'toHaveText is an asynchronous locator assertion that retries until the element text matches or times out.',
    reference: playwrightAssertionsReference,
  },
  {
    id: 'playwright.drag-before-each-hook',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Run this navigation before each test in the file.',
    instruction: 'Choose the per-test setup hook.',
    template: { before: 'test.', after: "(async ({ page }) => {\n  await page.goto('/')\n})" },
    options: [
      { id: 'before-each', label: 'beforeEach', code: 'beforeEach' },
      { id: 'before-all', label: 'beforeAll', code: 'beforeAll' },
      { id: 'after-each', label: 'afterEach', code: 'afterEach' },
      { id: 'skip', label: 'skip', code: 'skip' },
    ],
    correctOptionId: 'before-each',
    explanation:
      'beforeEach runs the navigation separately for every test and works with each test’s isolated page fixture.',
    reference: playwrightFixturesReference,
  },
  {
    id: 'playwright.drag-custom-fixture',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Create a customized test API with an additional dashboard fixture.',
    instruction: 'Choose the method that extends the base fixtures.',
    template: {
      before: 'const test = base.',
      after: '<{ dashboard: DashboardPage }>({\n  // fixture\n})',
    },
    options: [
      { id: 'extend', label: 'extend', code: 'extend' },
      { id: 'describe', label: 'describe', code: 'describe' },
      { id: 'configure', label: 'configure', code: 'configure' },
      { id: 'provide', label: 'provide', code: 'provide' },
    ],
    correctOptionId: 'extend',
    explanation:
      'test.extend creates a customized test function whose typed fixture object adds reusable setup and teardown.',
    reference: playwrightFixturesReference,
  },
  {
    id: 'playwright.drag-define-config',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Wrap the exported Playwright configuration with its typed helper.',
    instruction: 'Choose the configuration helper.',
    template: { before: 'export default ', after: "({\n  testDir: './e2e'\n})" },
    options: [
      { id: 'define-config', label: 'defineConfig', code: 'defineConfig' },
      { id: 'test-config', label: 'testConfig', code: 'testConfig' },
      { id: 'create-project', label: 'createProject', code: 'createProject' },
      { id: 'use-config', label: 'useConfig', code: 'useConfig' },
    ],
    correctOptionId: 'define-config',
    explanation:
      'defineConfig provides type-safe Playwright configuration and returns the object exported by playwright.config.ts.',
    reference: playwrightConfigurationReference,
  },
  {
    id: 'playwright.drag-device-project',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Apply Playwright’s desktop Chromium device settings to this project.',
    instruction: 'Choose the built-in device descriptor.',
    template: { before: "{ name: 'chromium', use: { ...devices[", after: '] } }' },
    options: [
      { id: 'chrome', label: "'Desktop Chrome'", code: "'Desktop Chrome'" },
      { id: 'chromium', label: "'Chromium Server'", code: "'Chromium Server'" },
      { id: 'browser', label: "'Browser Default'", code: "'Browser Default'" },
      { id: 'desktop', label: "'Desktop Generic'", code: "'Desktop Generic'" },
    ],
    correctOptionId: 'chrome',
    explanation:
      'The Desktop Chrome device descriptor supplies the browser and desktop context settings for the named project.',
    reference: playwrightProjectsReference,
  },
  {
    id: 'playwright.drag-trace-mode',
    topicId: 'playwright',
    kind: 'drag-blank',
    prompt: 'Record a trace on the first retry without tracing every successful first attempt.',
    instruction: 'Choose the trace mode string.',
    template: { before: 'use: { trace: ', after: ' }' },
    options: [
      { id: 'first-retry', label: "'on-first-retry'", code: "'on-first-retry'" },
      { id: 'retain-failure', label: "'retain-on-failure'", code: "'retain-on-failure'" },
      { id: 'on', label: "'on'", code: "'on'" },
      { id: 'off', label: "'off'", code: "'off'" },
    ],
    correctOptionId: 'first-retry',
    explanation:
      'The on-first-retry mode captures diagnostic trace data specifically for a test’s first retry attempt.',
    reference: playwrightConfigurationReference,
  },
] as const satisfies readonly DragBlankQuestion[]
