import type { DragBlankQuestion } from '../../../types'
import {
  dotnetCliReference,
  dotnetDependencyInjectionReference,
  dotnetGenericHostReference,
  dotnetLoggingReference,
  dotnetManagedExecutionReference,
  dotnetReferenceAddReference,
  dotnetRidReference,
  dotnetSdkReference,
  dotnetSingleFileReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'modern-dotnet.drag.development-install',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Choose the .NET installation needed to create, build, and run applications.',
    instruction: 'Select the installation that includes development tooling.',
    template: { before: 'Install the .NET ', after: ' on the development machine.' },
    options: [
      { id: 'sdk', label: 'SDK', code: 'SDK' },
      { id: 'runtime', label: 'runtime only', code: 'runtime only' },
      { id: 'gc', label: 'garbage collector only', code: 'garbage collector only' },
      { id: 'shared-library', label: 'shared library only', code: 'shared library only' },
    ],
    correctOptionId: 'sdk',
    explanation:
      'The .NET SDK includes the CLI and build tools as well as a runtime for developing and running applications.',
    reference: dotnetSdkReference,
  },
  {
    id: 'modern-dotnet.drag.run-project',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Launch the selected project from source during development.',
    instruction: 'Select the CLI command that builds when needed and runs the app.',
    template: { before: '', after: ' --project src/WorkerTool' },
    options: [
      { id: 'run', label: 'dotnet run', code: 'dotnet run' },
      { id: 'restore', label: 'dotnet restore', code: 'dotnet restore' },
      { id: 'pack', label: 'dotnet pack', code: 'dotnet pack' },
      { id: 'clean', label: 'dotnet clean', code: 'dotnet clean' },
    ],
    correctOptionId: 'run',
    explanation:
      'dotnet run provides a convenient development workflow that builds the project when necessary and launches it.',
    reference: dotnetCliReference,
  },
  {
    id: 'modern-dotnet.drag.release-build',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Build the project with its Release configuration.',
    instruction: 'Select the configuration name used for optimized release output.',
    template: { before: 'dotnet build -c ', after: '' },
    options: [
      { id: 'release', label: 'Release', code: 'Release' },
      { id: 'debug', label: 'Debug', code: 'Debug' },
      { id: 'runtime', label: 'Runtime', code: 'Runtime' },
      { id: 'publish', label: 'Publish', code: 'Publish' },
    ],
    correctOptionId: 'release',
    explanation:
      'The -c option selects a named build configuration, and Release is the conventional optimized configuration.',
    reference: dotnetCliReference,
  },
  {
    id: 'modern-dotnet.drag.project-dependency',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Reference a sibling Core project from an SDK-style app project.',
    instruction: 'Select the MSBuild item intended for a project-to-project dependency.',
    template: { before: '<', after: ' Include="../Core/Core.csproj" />' },
    options: [
      { id: 'project-reference', label: 'ProjectReference', code: 'ProjectReference' },
      { id: 'package-reference', label: 'PackageReference', code: 'PackageReference' },
      { id: 'target-framework', label: 'TargetFramework', code: 'TargetFramework' },
      { id: 'runtime-id', label: 'RuntimeIdentifier', code: 'RuntimeIdentifier' },
    ],
    correctOptionId: 'project-reference',
    explanation:
      'ProjectReference adds another project to the build dependency graph and references its resulting assembly.',
    reference: dotnetReferenceAddReference,
  },
  {
    id: 'modern-dotnet.drag.jit-compilation',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt:
      'Identify the normal runtime step that converts intermediate language into native instructions.',
    instruction: 'Select the compilation mechanism used as managed methods execute.',
    template: { before: 'IL method body → ', after: ' → native machine code' },
    options: [
      { id: 'jit', label: 'JIT compiler', code: 'JIT compiler' },
      { id: 'nuget', label: 'NuGet restore', code: 'NuGet restore' },
      { id: 'json', label: 'configuration provider', code: 'configuration provider' },
      { id: 'logger', label: 'logging provider', code: 'logging provider' },
    ],
    correctOptionId: 'jit',
    explanation:
      'The just-in-time compiler translates a managed method from intermediate language into native code for the current machine.',
    reference: dotnetManagedExecutionReference,
  },
  {
    id: 'modern-dotnet.drag.host-builder',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Create a Generic Host application builder with the conventional defaults.',
    instruction: 'Select the host factory call.',
    template: { before: 'HostApplicationBuilder builder = ', after: ';' },
    options: [
      {
        id: 'create-app',
        label: 'Host.CreateApplicationBuilder(args)',
        code: 'Host.CreateApplicationBuilder(args)',
      },
      { id: 'new-host', label: 'new Host(args)', code: 'new Host(args)' },
      { id: 'build-now', label: 'Host.Build(args)', code: 'Host.Build(args)' },
      { id: 'runtime-create', label: 'Runtime.CreateHost(args)', code: 'Runtime.CreateHost(args)' },
    ],
    correctOptionId: 'create-app',
    explanation:
      'Host.CreateApplicationBuilder creates the modern host builder and applies default configuration and logging providers.',
    reference: dotnetGenericHostReference,
  },
  {
    id: 'modern-dotnet.drag.transient-service',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Register a new JobFormatter instance for each service resolution.',
    instruction: 'Select the registration method for the transient lifetime.',
    template: { before: 'builder.Services.', after: '<IJobFormatter, JobFormatter>();' },
    options: [
      { id: 'transient', label: 'AddTransient', code: 'AddTransient' },
      { id: 'singleton', label: 'AddSingleton', code: 'AddSingleton' },
      { id: 'hosted', label: 'AddHostedService', code: 'AddHostedService' },
      { id: 'options', label: 'Configure', code: 'Configure' },
    ],
    correctOptionId: 'transient',
    explanation:
      'AddTransient tells the container to create a new service instance whenever the service is requested.',
    reference: dotnetDependencyInjectionReference,
  },
  {
    id: 'modern-dotnet.drag.typed-logger',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Inject a logger whose category is associated with Worker.',
    instruction: 'Select the typed logging abstraction.',
    template: { before: 'public Worker(', after: ' logger) { /* ... */ }' },
    options: [
      { id: 'typed-logger', label: 'ILogger<Worker>', code: 'ILogger<Worker>' },
      { id: 'console', label: 'Console', code: 'Console' },
      { id: 'provider', label: 'ILoggingProvider', code: 'ILoggingProvider' },
      { id: 'configuration', label: 'IConfiguration', code: 'IConfiguration' },
    ],
    correctOptionId: 'typed-logger',
    explanation:
      'ILogger<Worker> is resolved by dependency injection and uses the Worker type name as its logging category.',
    reference: dotnetLoggingReference,
  },
  {
    id: 'modern-dotnet.drag.linux-rid',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Publish a self-contained application for 64-bit Linux on Intel or AMD hardware.',
    instruction: 'Select the matching runtime identifier.',
    template: { before: 'dotnet publish -r ', after: ' --self-contained true' },
    options: [
      { id: 'linux-x64', label: 'linux-x64', code: 'linux-x64' },
      { id: 'linux-arm64', label: 'linux-arm64', code: 'linux-arm64' },
      { id: 'win-x64', label: 'win-x64', code: 'win-x64' },
      { id: 'net10', label: 'net10.0', code: 'net10.0' },
    ],
    correctOptionId: 'linux-x64',
    explanation:
      'linux-x64 identifies Linux as the operating system and x64 as the target processor architecture.',
    reference: dotnetRidReference,
  },
  {
    id: 'modern-dotnet.drag.single-file',
    topicId: 'modern-dotnet',
    kind: 'drag-blank',
    prompt: 'Enable single-file analysis and publishing in the project file.',
    instruction: 'Select the MSBuild property for a single-file bundle.',
    template: { before: '<', after: '>true</PublishSingleFile>' },
    options: [
      { id: 'single-file', label: 'PublishSingleFile', code: 'PublishSingleFile' },
      { id: 'target', label: 'TargetFramework', code: 'TargetFramework' },
      { id: 'nullable', label: 'Nullable', code: 'Nullable' },
      { id: 'output', label: 'OutputType', code: 'OutputType' },
    ],
    correctOptionId: 'single-file',
    explanation:
      'PublishSingleFile enables the single-file publishing mode and its compatibility analysis during build.',
    reference: dotnetSingleFileReference,
  },
] as const satisfies readonly DragBlankQuestion[]
