import type { TextBlankQuestion } from '../../../types'
import {
  dotnetCliReference,
  dotnetConfigurationReference,
  dotnetDependencyInjectionReference,
  dotnetDeploymentReference,
  dotnetPackageReference,
  dotnetProjectSdkReference,
  dotnetSdkReference,
  dotnetTargetFrameworkReference,
  dotnetTestReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'modern-dotnet.text.cli-info',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Complete the command that displays detailed SDK and runtime information.',
    instruction: 'Type the missing dotnet option.',
    template: { before: 'dotnet ', after: '' },
    canonicalAnswer: '--info',
    acceptedAnswers: ['--info'],
    explanation:
      'The --info option reports the active SDK, host, installed workloads, runtimes, architecture, and environment details.',
    reference: dotnetSdkReference,
  },
  {
    id: 'modern-dotnet.text.new-console',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Complete the command that creates a new console application.',
    instruction: 'Type the missing template short name.',
    template: { before: 'dotnet new ', after: ' -n WorkerTool' },
    canonicalAnswer: 'console',
    acceptedAnswers: ['console'],
    explanation:
      'console is the built-in template short name used by dotnet new to create a console application project.',
    reference: dotnetCliReference,
  },
  {
    id: 'modern-dotnet.text.restore-command',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Complete the explicit command that resolves project dependencies.',
    instruction: 'Type the missing dotnet command.',
    template: { before: 'dotnet ', after: '' },
    canonicalAnswer: 'restore',
    acceptedAnswers: ['restore'],
    explanation:
      'dotnet restore resolves NuGet dependencies and prepares the assets information consumed by later build operations.',
    reference: dotnetCliReference,
  },
  {
    id: 'modern-dotnet.text.project-sdk',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Select the general-purpose SDK used by this SDK-style project.',
    instruction: 'Type the missing value inside the Sdk attribute.',
    template: { before: '<Project Sdk="', after: '">\n</Project>' },
    canonicalAnswer: 'Microsoft.NET.Sdk',
    acceptedAnswers: ['Microsoft.NET.Sdk'],
    explanation:
      'Microsoft.NET.Sdk supplies the common build targets and conventions for .NET applications and libraries.',
    reference: dotnetProjectSdkReference,
  },
  {
    id: 'modern-dotnet.text.target-net10',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Target the cross-platform .NET 10 API set.',
    instruction: 'Type the missing target framework moniker.',
    template: { before: '<TargetFramework>', after: '</TargetFramework>' },
    canonicalAnswer: 'net10.0',
    acceptedAnswers: ['net10.0'],
    explanation:
      'net10.0 is the target framework moniker for the general-purpose .NET 10 API surface.',
    reference: dotnetTargetFrameworkReference,
  },
  {
    id: 'modern-dotnet.text.package-reference',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Complete the item that declares a NuGet package dependency.',
    instruction: 'Type the missing MSBuild item name.',
    template: {
      before: '<',
      after: ' Include="Humanizer" Version="2.14.1" />',
    },
    canonicalAnswer: 'PackageReference',
    acceptedAnswers: ['PackageReference'],
    explanation:
      'PackageReference is the SDK-style project item that identifies an external NuGet package and version.',
    reference: dotnetPackageReference,
  },
  {
    id: 'modern-dotnet.text.singleton-registration',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Register one IClock service instance for the lifetime of the service provider.',
    instruction: 'Type the missing dependency injection registration method.',
    template: { before: 'builder.Services.', after: '<IClock, SystemClock>();' },
    canonicalAnswer: 'AddSingleton',
    acceptedAnswers: ['AddSingleton'],
    explanation:
      'AddSingleton registers the implementation so the container creates and reuses one instance for its lifetime.',
    reference: dotnetDependencyInjectionReference,
  },
  {
    id: 'modern-dotnet.text.appsettings-file',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt:
      'Name the conventional base JSON configuration file loaded by the default Generic Host.',
    instruction: 'Type the complete file name.',
    template: { before: 'Configuration file: ', after: '' },
    canonicalAnswer: 'appsettings.json',
    acceptedAnswers: ['appsettings.json'],
    explanation:
      'The default host configuration pipeline loads appsettings.json before environment-specific and later configuration providers.',
    reference: dotnetConfigurationReference,
  },
  {
    id: 'modern-dotnet.text.test-command',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Complete the command that builds and runs configured test projects.',
    instruction: 'Type the missing dotnet command.',
    template: { before: 'dotnet ', after: ' -c Release' },
    canonicalAnswer: 'test',
    acceptedAnswers: ['test'],
    explanation:
      'dotnet test builds the selected test projects and delegates execution to their configured test runner.',
    reference: dotnetTestReference,
  },
  {
    id: 'modern-dotnet.text.self-contained',
    topicId: 'modern-dotnet',
    kind: 'text-blank',
    prompt: 'Publish for Linux x64 and include the .NET runtime in the output.',
    instruction: 'Type the option and value that enable self-contained deployment.',
    template: { before: 'dotnet publish -c Release -r linux-x64 ', after: '' },
    canonicalAnswer: '--self-contained true',
    acceptedAnswers: ['--self-contained true'],
    explanation:
      'The --self-contained true option includes the runtime selected by the linux-x64 runtime identifier in the published output.',
    reference: dotnetDeploymentReference,
  },
] as const satisfies readonly TextBlankQuestion[]
