import type { DragBlankQuestion } from '../../../types'
import {
  seleniumActionsReference,
  seleniumElementInteractionsReference,
  seleniumFindersReference,
  seleniumFramesReference,
  seleniumIsolationReference,
  seleniumLocatorsReference,
  seleniumSelectListsReference,
  seleniumTroubleshootingReference,
  seleniumWaitsReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'selenium.drag.fixture-yield',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Provide the browser to the test before fixture cleanup runs.',
    instruction: 'Choose the pytest keyword that pauses the fixture at its handoff point.',
    template: {
      before: 'browser = webdriver.Chrome()\n',
      after: ' browser\nbrowser.quit()',
    },
    options: [
      { id: 'yield', label: 'yield', code: 'yield' },
      { id: 'return', label: 'return', code: 'return' },
      { id: 'await', label: 'await', code: 'await' },
      { id: 'pass', label: 'pass', code: 'pass' },
    ],
    correctOptionId: 'yield',
    explanation:
      'A yielding pytest fixture hands the browser to the test, then resumes afterward to run driver cleanup.',
    reference: seleniumIsolationReference,
  },
  {
    id: 'selenium.drag.css-locator',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Locate the Save button with a CSS selector.',
    instruction: 'Choose the Selenium By strategy for CSS syntax.',
    template: { before: 'driver.find_element(By.', after: ", '[data-testid=save]')" },
    options: [
      { id: 'css', label: 'CSS_SELECTOR', code: 'CSS_SELECTOR' },
      { id: 'class', label: 'CLASS_NAME', code: 'CLASS_NAME' },
      { id: 'id', label: 'ID', code: 'ID' },
      { id: 'xpath', label: 'XPATH', code: 'XPATH' },
    ],
    correctOptionId: 'css',
    explanation:
      'By.CSS_SELECTOR tells WebDriver to interpret the supplied value as a CSS selector expression.',
    reference: seleniumLocatorsReference,
  },
  {
    id: 'selenium.drag.find-collection',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Return a list containing every matching table row.',
    instruction: 'Choose the plural WebDriver finder.',
    template: { before: 'rows = driver.', after: "(By.CSS_SELECTOR, 'tbody tr')" },
    options: [
      { id: 'many', label: 'find_elements', code: 'find_elements' },
      { id: 'one', label: 'find_element', code: 'find_element' },
      { id: 'all', label: 'get_elements', code: 'get_elements' },
      { id: 'query', label: 'query_all', code: 'query_all' },
    ],
    correctOptionId: 'many',
    explanation:
      'find_elements returns a list containing all matches and returns an empty list when nothing matches.',
    reference: seleniumFindersReference,
  },
  {
    id: 'selenium.drag.clear-field',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Remove the existing value before typing replacement text.',
    instruction: 'Choose the WebElement method that empties an editable field.',
    template: { before: 'name_field.', after: "()\nname_field.send_keys('Ada')" },
    options: [
      { id: 'clear', label: 'clear', code: 'clear' },
      { id: 'reset', label: 'reset', code: 'reset' },
      { id: 'delete', label: 'delete', code: 'delete' },
      { id: 'erase', label: 'erase', code: 'erase' },
    ],
    correctOptionId: 'clear',
    explanation:
      'The clear method removes the current contents of an editable text field before new keys are sent.',
    reference: seleniumElementInteractionsReference,
  },
  {
    id: 'selenium.drag.select-wrapper',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Wrap the native country dropdown with Selenium support functionality.',
    instruction: 'Choose the class designed for native select elements.',
    template: { before: 'country = ', after: "(driver.find_element(By.ID, 'country'))" },
    options: [
      { id: 'select', label: 'Select', code: 'Select' },
      { id: 'options', label: 'Options', code: 'Options' },
      { id: 'dropdown', label: 'Dropdown', code: 'Dropdown' },
      { id: 'choices', label: 'Choices', code: 'Choices' },
    ],
    correctOptionId: 'select',
    explanation:
      'The Select support class wraps a native HTML select element and exposes operations for choosing its options.',
    reference: seleniumSelectListsReference,
  },
  {
    id: 'selenium.drag.wait-until',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Poll the expected condition until it succeeds or the explicit wait times out.',
    instruction: 'Choose the WebDriverWait method that evaluates the condition.',
    template: {
      before: 'message = wait.',
      after: "(EC.visibility_of_element_located((By.ID, 'message')))",
    },
    options: [
      { id: 'until', label: 'until', code: 'until' },
      { id: 'sleep', label: 'sleep', code: 'sleep' },
      { id: 'find', label: 'find', code: 'find' },
      { id: 'retry', label: 'retry', code: 'retry' },
    ],
    correctOptionId: 'until',
    explanation:
      'WebDriverWait.until repeatedly evaluates the supplied callable and returns once it produces a successful value.',
    reference: seleniumWaitsReference,
  },
  {
    id: 'selenium.drag.default-content',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Return from an iframe to the top-level page.',
    instruction: 'Choose the switch_to method that restores the default browsing context.',
    template: { before: 'driver.switch_to.', after: '()' },
    options: [
      { id: 'default', label: 'default_content', code: 'default_content' },
      { id: 'parent', label: 'parent_window', code: 'parent_window' },
      { id: 'main', label: 'main_page', code: 'main_page' },
      { id: 'root', label: 'root_frame', code: 'root_frame' },
    ],
    correctOptionId: 'default',
    explanation:
      'switch_to.default_content restores the top-level document after WebDriver has interacted inside a frame.',
    reference: seleniumFramesReference,
  },
  {
    id: 'selenium.drag.action-chains',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Create an action sequence for coordinated pointer input.',
    instruction: 'Choose the Selenium Python convenience class for chained actions.',
    template: { before: 'actions = ', after: '(driver)' },
    options: [
      { id: 'chains', label: 'ActionChains', code: 'ActionChains' },
      { id: 'builder', label: 'ActionBuilder', code: 'ActionBuilder' },
      { id: 'pointer', label: 'PointerActions', code: 'PointerActions' },
      { id: 'events', label: 'BrowserEvents', code: 'BrowserEvents' },
    ],
    correctOptionId: 'chains',
    explanation:
      'ActionChains provides the Python convenience API for assembling mouse and keyboard actions against a driver.',
    reference: seleniumActionsReference,
  },
  {
    id: 'selenium.drag.perform-actions',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Execute the mouse actions that have been assembled in the chain.',
    instruction: 'Choose the method that sends the actions to the browser.',
    template: { before: 'ActionChains(driver).move_to_element(menu).click(item).', after: '()' },
    options: [
      { id: 'perform', label: 'perform', code: 'perform' },
      { id: 'execute', label: 'execute', code: 'execute' },
      { id: 'dispatch', label: 'dispatch', code: 'dispatch' },
      { id: 'run', label: 'run', code: 'run' },
    ],
    correctOptionId: 'perform',
    explanation:
      'perform sends the complete action sequence to the browser for coordinated execution.',
    reference: seleniumActionsReference,
  },
  {
    id: 'selenium.drag.refind-stale',
    topicId: 'selenium',
    kind: 'drag-blank',
    prompt: 'Obtain a fresh Save button reference after the DOM replaced the old element.',
    instruction: 'Choose the finder used after waiting for the updated DOM state.',
    template: { before: 'save_button = driver.', after: "(By.ID, 'save')" },
    options: [
      { id: 'find', label: 'find_element', code: 'find_element' },
      { id: 'refresh', label: 'refresh_element', code: 'refresh_element' },
      { id: 'restore', label: 'restore_element', code: 'restore_element' },
      { id: 'reuse', label: 'reuse_element', code: 'reuse_element' },
    ],
    correctOptionId: 'find',
    explanation:
      'A stale reference does not relocate itself, so the test must find the element again after the DOM update.',
    reference: seleniumTroubleshootingReference,
  },
] as const satisfies readonly DragBlankQuestion[]
