import type { TextBlankQuestion } from '../../../types'
import {
  seleniumAlertsReference,
  seleniumElementInteractionsReference,
  seleniumFindersReference,
  seleniumFirstScriptReference,
  seleniumLocatorsReference,
  seleniumWaitsReference,
  seleniumWindowsReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'selenium.text.chrome-session',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the call that starts a Chrome WebDriver session.',
    instruction: 'Type the missing webdriver class name.',
    template: { before: 'driver = webdriver.', after: '()' },
    canonicalAnswer: 'Chrome',
    acceptedAnswers: ['Chrome'],
    explanation:
      'webdriver.Chrome creates a new WebDriver session connected to a Chrome browser instance.',
    reference: seleniumFirstScriptReference,
  },
  {
    id: 'selenium.text.navigate',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the WebDriver call that navigates to the login page.',
    instruction: 'Type the missing navigation method.',
    template: { before: 'driver.', after: "('https://example.com/login')" },
    canonicalAnswer: 'get',
    acceptedAnswers: ['get'],
    explanation:
      'driver.get loads the supplied URL in the browser controlled by the current WebDriver session.',
    reference: seleniumFirstScriptReference,
  },
  {
    id: 'selenium.text.id-locator',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the locator that targets the element whose id is email.',
    instruction: 'Type the missing By strategy constant.',
    template: { before: 'driver.find_element(By.', after: ", 'email')" },
    canonicalAnswer: 'ID',
    acceptedAnswers: ['ID'],
    explanation:
      'By.ID selects an element by its HTML id value and is preferred when that id is unique and stable.',
    reference: seleniumLocatorsReference,
  },
  {
    id: 'selenium.text.find-element',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the singular finder for the Save button.',
    instruction: 'Type the missing WebDriver method name.',
    template: { before: 'save = driver.', after: "(By.ID, 'save')" },
    canonicalAnswer: 'find_element',
    acceptedAnswers: ['find_element'],
    explanation:
      'find_element returns the first matching WebElement and raises an exception if no match is found.',
    reference: seleniumFindersReference,
  },
  {
    id: 'selenium.text.send-keys',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the field interaction that types an email address.',
    instruction: 'Type the missing WebElement method name.',
    template: { before: 'email_field.', after: "('ada@example.com')" },
    canonicalAnswer: 'send_keys',
    acceptedAnswers: ['send_keys'],
    explanation:
      'send_keys types the supplied characters into a keyboard-interactable element such as a text input.',
    reference: seleniumElementInteractionsReference,
  },
  {
    id: 'selenium.text.webdriver-wait',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the explicit wait with a ten-second timeout.',
    instruction: 'Type the missing Selenium support class.',
    template: { before: 'wait = ', after: '(driver, 10)' },
    canonicalAnswer: 'WebDriverWait',
    acceptedAnswers: ['WebDriverWait'],
    explanation:
      'WebDriverWait creates an explicit wait that polls a condition until it succeeds or ten seconds elapse.',
    reference: seleniumWaitsReference,
  },
  {
    id: 'selenium.text.visible-condition',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the expected condition that waits for a visible status element.',
    instruction: 'Type the missing expected-condition function.',
    template: { before: 'status = wait.until(EC.', after: "((By.ID, 'status')))" },
    canonicalAnswer: 'visibility_of_element_located',
    acceptedAnswers: ['visibility_of_element_located'],
    explanation:
      'visibility_of_element_located waits for a matching element to exist and have a visible size before returning it.',
    reference: seleniumWaitsReference,
  },
  {
    id: 'selenium.text.alert-context',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the property that switches WebDriver to the open JavaScript alert.',
    instruction: 'Type the missing switch_to property name.',
    template: { before: 'alert = driver.switch_to.', after: '' },
    canonicalAnswer: 'alert',
    acceptedAnswers: ['alert'],
    explanation:
      'driver.switch_to.alert returns the currently displayed alert so the test can inspect, accept, or dismiss it.',
    reference: seleniumAlertsReference,
  },
  {
    id: 'selenium.text.window-switch',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the call that switches control to new_handle.',
    instruction: 'Type the missing switch_to method name.',
    template: { before: 'driver.switch_to.', after: '(new_handle)' },
    canonicalAnswer: 'window',
    acceptedAnswers: ['window'],
    explanation:
      'switch_to.window changes the active browsing context to the window or tab represented by the supplied handle.',
    reference: seleniumWindowsReference,
  },
  {
    id: 'selenium.text.quit-session',
    topicId: 'selenium',
    kind: 'text-blank',
    prompt: 'Complete the cleanup that ends the entire WebDriver session.',
    instruction: 'Type the missing driver method name.',
    template: { before: 'driver.', after: '()' },
    canonicalAnswer: 'quit',
    acceptedAnswers: ['quit'],
    explanation:
      'driver.quit closes every associated browser window and ends the WebDriver session completely.',
    reference: seleniumFirstScriptReference,
  },
] as const satisfies readonly TextBlankQuestion[]
