import type { DragBlankQuestion } from '../../../types'
import {
  csharpBuiltInTypesReference,
  csharpCollectionsReference,
  csharpConsoleReference,
  csharpIterationReference,
  csharpMethodsReference,
  csharpOperatorsReference,
  csharpPropertiesReference,
  csharpSelectionReference,
  csharpTypesReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'csharp-basics.drag.console-output',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Write the score to the console followed by a newline.',
    instruction: 'Select the correct Console member.',
    template: { before: '', after: '(score);' },
    options: [
      { id: 'write-line', label: 'Console.WriteLine', code: 'Console.WriteLine' },
      { id: 'read-line', label: 'Console.ReadLine', code: 'Console.ReadLine' },
      { id: 'write', label: 'Console.Write', code: 'Console.Write' },
      { id: 'print', label: 'Console.Print', code: 'Console.Print' },
    ],
    correctOptionId: 'write-line',
    explanation:
      'Console.WriteLine writes the supplied value and then moves output to the beginning of a new line.',
    reference: csharpConsoleReference,
  },
  {
    id: 'csharp-basics.drag.const-declaration',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Declare MaxScore as an integer constant.',
    instruction: 'Select the modifier that prevents later assignment.',
    template: { before: '', after: ' int MaxScore = 100;' },
    options: [
      { id: 'const', label: 'const', code: 'const' },
      { id: 'var', label: 'var', code: 'var' },
      { id: 'void', label: 'void', code: 'void' },
      { id: 'new', label: 'new', code: 'new' },
    ],
    correctOptionId: 'const',
    explanation:
      'The const modifier declares a compile-time constant that cannot be assigned a different value.',
    reference: csharpBuiltInTypesReference,
  },
  {
    id: 'csharp-basics.drag.inferred-local',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Let the compiler infer the local type from the string initializer.',
    instruction: 'Select the contextual keyword for an implicitly typed local variable.',
    template: { before: '', after: ' name = "Ada";' },
    options: [
      { id: 'var', label: 'var', code: 'var' },
      { id: 'auto', label: 'auto', code: 'auto' },
      { id: 'let', label: 'let', code: 'let' },
      { id: 'dynamic-type', label: 'type', code: 'type' },
    ],
    correctOptionId: 'var',
    explanation:
      'var instructs the compiler to infer the local variable’s static type from its required initializer.',
    reference: csharpTypesReference,
  },
  {
    id: 'csharp-basics.drag.floating-division',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Convert total before division so average keeps its fractional part.',
    instruction: 'Select the explicit conversion expression.',
    template: { before: 'double average = ', after: ' / count;' },
    options: [
      { id: 'double-cast', label: '(double)total', code: '(double)total' },
      { id: 'unchanged', label: 'total', code: 'total' },
      { id: 'int-cast', label: '(int)total', code: '(int)total' },
      { id: 'boolean-cast', label: '(bool)total', code: '(bool)total' },
    ],
    correctOptionId: 'double-cast',
    explanation:
      'Casting total to double makes the division floating-point instead of integer division.',
    reference: csharpOperatorsReference,
  },
  {
    id: 'csharp-basics.drag.logical-or',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Allow access when the user is an owner or an administrator.',
    instruction: 'Select the operator that accepts either true condition.',
    template: { before: 'if (isOwner ', after: ' isAdmin) {\n    Allow();\n}' },
    options: [
      { id: 'or', label: '||', code: '||' },
      { id: 'and', label: '&&', code: '&&' },
      { id: 'equal', label: '==', code: '==' },
      { id: 'not', label: '!', code: '!' },
    ],
    correctOptionId: 'or',
    explanation:
      'The conditional OR operator || produces true when either one or both operands are true.',
    reference: csharpOperatorsReference,
  },
  {
    id: 'csharp-basics.drag.switch-break',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Finish the matching switch section after changing running.',
    instruction: 'Select the statement that exits the switch.',
    template: {
      before: 'case "quit":\n    running = false;\n    ',
      after: ';\ndefault:\n    ShowHelp();\n    break;',
    },
    options: [
      { id: 'break', label: 'break', code: 'break' },
      { id: 'continue', label: 'continue', code: 'continue' },
      { id: 'return-value', label: 'return true', code: 'return true' },
      { id: 'else', label: 'else', code: 'else' },
    ],
    correctOptionId: 'break',
    explanation:
      'break completes the switch section and transfers control to the statement after the switch.',
    reference: csharpSelectionReference,
  },
  {
    id: 'csharp-basics.drag.foreach-loop',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Visit every integer stored in scores.',
    instruction: 'Select the correct foreach loop header.',
    template: { before: '', after: ' {\n    Console.WriteLine(score);\n}' },
    options: [
      {
        id: 'foreach',
        label: 'foreach (int score in scores)',
        code: 'foreach (int score in scores)',
      },
      { id: 'for-in', label: 'for (int score in scores)', code: 'for (int score in scores)' },
      {
        id: 'foreach-of',
        label: 'foreach (int score of scores)',
        code: 'foreach (int score of scores)',
      },
      { id: 'while-in', label: 'while (int score in scores)', code: 'while (int score in scores)' },
    ],
    correctOptionId: 'foreach',
    explanation:
      'A C# foreach header declares an iteration variable, uses in, and then names the collection.',
    reference: csharpIterationReference,
  },
  {
    id: 'csharp-basics.drag.method-result',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Declare DoubleValue as a method that returns an integer.',
    instruction: 'Select the return type that matches the returned expression.',
    template: { before: 'static ', after: ' DoubleValue(int value) {\n    return value * 2;\n}' },
    options: [
      { id: 'int', label: 'int', code: 'int' },
      { id: 'void', label: 'void', code: 'void' },
      { id: 'return', label: 'return', code: 'return' },
      { id: 'var', label: 'var', code: 'var' },
    ],
    correctOptionId: 'int',
    explanation:
      'The return type appears before the method name, and int matches the integer expression returned.',
    reference: csharpMethodsReference,
  },
  {
    id: 'csharp-basics.drag.list-type',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Declare a resizable collection of integers.',
    instruction: 'Select the generic list type that matches the initializer.',
    template: { before: '', after: ' scores = new() { 80, 90, 100 };' },
    options: [
      { id: 'list-int', label: 'List<int>', code: 'List<int>' },
      { id: 'array-int', label: 'int[]', code: 'int[]' },
      { id: 'list-string', label: 'List<string>', code: 'List<string>' },
      { id: 'int', label: 'int', code: 'int' },
    ],
    correctOptionId: 'list-int',
    explanation:
      'List<int> is a generic, resizable collection whose elements all have the int type.',
    reference: csharpCollectionsReference,
  },
  {
    id: 'csharp-basics.drag.class-property',
    topicId: 'csharp-basics',
    kind: 'drag-blank',
    prompt: 'Add a public read-write Name property to Person.',
    instruction: 'Select the auto-property declaration.',
    template: { before: 'public class Person {\n    ', after: '\n}' },
    options: [
      {
        id: 'property',
        label: 'public string Name { get; set; } = "";',
        code: 'public string Name { get; set; } = "";',
      },
      { id: 'local', label: 'string Name = "";', code: 'string Name = "";' },
      { id: 'method', label: 'public string Name();', code: 'public string Name();' },
      { id: 'invalid', label: 'public Name: string;', code: 'public Name: string;' },
    ],
    correctOptionId: 'property',
    explanation:
      'The public string declaration with get and set defines a readable and writable auto-property.',
    reference: csharpPropertiesReference,
  },
] as const satisfies readonly DragBlankQuestion[]
