import type { SequenceQuestion } from '../../../types'
import {
  csharpClassesReference,
  csharpCollectionsReference,
  csharpConsoleReference,
  csharpIterationReference,
  csharpMethodsReference,
  csharpOperatorsReference,
  csharpSelectionReference,
  csharpTopLevelReference,
} from './shared'

export const sequenceQuestions = [
  {
    id: 'csharp-basics.sequence.greeting',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a top-level program that builds and writes a greeting.',
    instruction: 'Declare the name, build the interpolated string, and then display it.',
    items: [
      { id: 'name', code: 'string name = "Ada";' },
      { id: 'greeting', code: 'string greeting = $"Hello, {name}!";' },
      { id: 'output', code: 'Console.WriteLine(greeting);' },
    ],
    correctOrder: ['name', 'greeting', 'output'],
    explanation:
      'name must exist before interpolation builds greeting, and greeting must exist before it is displayed.',
    reference: csharpTopLevelReference,
  },
  {
    id: 'csharp-basics.sequence.console-prompt',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange console output that shows a prompt and then a result.',
    instruction: 'Write the prompt, prepare the value, and display the completed message.',
    items: [
      { id: 'prompt', code: 'Console.Write("Score: ");' },
      { id: 'score', code: 'int score = 95;' },
      { id: 'output', code: 'Console.WriteLine(score);' },
    ],
    correctOrder: ['prompt', 'score', 'output'],
    explanation:
      'The prompt is written first, score is initialized before use, and WriteLine displays the value and ends the line.',
    reference: csharpConsoleReference,
  },
  {
    id: 'csharp-basics.sequence.floating-average',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange the declarations that calculate and display a fractional average.',
    instruction: 'Prepare both integer operands, convert before division, and then use the result.',
    items: [
      { id: 'total', code: 'int total = 7;' },
      { id: 'count', code: 'int count = 2;' },
      { id: 'average', code: 'double average = (double)total / count;' },
      { id: 'output', code: 'Console.WriteLine(average);' },
    ],
    correctOrder: ['total', 'count', 'average', 'output'],
    acceptedOrders: [['count', 'total', 'average', 'output']],
    explanation:
      'total and count may be declared in either order, but both must exist before average is calculated and displayed.',
    reference: csharpOperatorsReference,
  },
  {
    id: 'csharp-basics.sequence.if-else-grade',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange the conditional that assigns and displays a grade.',
    instruction: 'Declare the values, complete both branches, and display the assigned grade.',
    items: [
      { id: 'score', code: 'int score = 85;' },
      { id: 'grade', code: "char grade = ' ';" },
      { id: 'if', code: 'if (score >= 90) {' },
      { id: 'a', code: "    grade = 'A';" },
      { id: 'else', code: '} else {' },
      { id: 'b', code: "    grade = 'B';" },
      { id: 'close', code: '}' },
      { id: 'output', code: 'Console.WriteLine(grade);' },
    ],
    correctOrder: ['score', 'grade', 'if', 'a', 'else', 'b', 'close', 'output'],
    acceptedOrders: [['grade', 'score', 'if', 'a', 'else', 'b', 'close', 'output']],
    explanation:
      'The independent declarations come first, each assignment stays in its branch, and output follows the completed conditional.',
    reference: csharpSelectionReference,
  },
  {
    id: 'csharp-basics.sequence.for-total',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange the loop that totals the integers from 1 through 3.',
    instruction: 'Initialize the accumulator, complete the loop, and then display the total.',
    items: [
      { id: 'total', code: 'int total = 0;' },
      { id: 'for', code: 'for (int value = 1; value <= 3; value++) {' },
      { id: 'add', code: '    total += value;' },
      { id: 'close', code: '}' },
      { id: 'output', code: 'Console.WriteLine(total);' },
    ],
    correctOrder: ['total', 'for', 'add', 'close', 'output'],
    explanation:
      'The accumulator exists before the loop, addition belongs in the loop body, and output occurs after all iterations.',
    reference: csharpIterationReference,
  },
  {
    id: 'csharp-basics.sequence.while-countdown',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a while loop that displays 3, 2, and 1.',
    instruction: 'Initialize the counter, test it, display it, and decrease it each iteration.',
    items: [
      { id: 'counter', code: 'int count = 3;' },
      { id: 'while', code: 'while (count > 0) {' },
      { id: 'output', code: '    Console.WriteLine(count);' },
      { id: 'decrement', code: '    count--;' },
      { id: 'close', code: '}' },
    ],
    correctOrder: ['counter', 'while', 'output', 'decrement', 'close'],
    explanation:
      'count is initialized before the condition, and each iteration prints its current value before decrementing.',
    reference: csharpIterationReference,
  },
  {
    id: 'csharp-basics.sequence.method-call',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a local method and top-level statements that use its result.',
    instruction: 'Define the method, call it, and then display the returned value.',
    items: [
      { id: 'method', code: 'static int Square(int value) {' },
      { id: 'method-return', code: '    return value * value;' },
      { id: 'method-close', code: '}' },
      { id: 'call', code: 'int result = Square(4);' },
      { id: 'output', code: 'Console.WriteLine(result);' },
    ],
    correctOrder: ['method', 'method-return', 'method-close', 'call', 'output'],
    explanation:
      'The method body returns its calculation, the call stores that result, and output uses the initialized variable.',
    reference: csharpMethodsReference,
  },
  {
    id: 'csharp-basics.sequence.array-loop',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a program that displays every value in an array.',
    instruction: 'Create the array, open the foreach loop, display an element, and close the loop.',
    items: [
      { id: 'array', code: 'int[] scores = { 80, 90, 100 };' },
      { id: 'foreach', code: 'foreach (int score in scores) {' },
      { id: 'output', code: '    Console.WriteLine(score);' },
      { id: 'close', code: '}' },
    ],
    correctOrder: ['array', 'foreach', 'output', 'close'],
    explanation:
      'The array must exist before foreach enumerates it, and output belongs inside the loop body.',
    reference: csharpCollectionsReference,
  },
  {
    id: 'csharp-basics.sequence.list-loop',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a program that appends to a list and displays every value.',
    instruction: 'Prepare the list, append a value, and then iterate over all elements.',
    items: [
      { id: 'list', code: 'List<int> scores = new() { 80, 90 };' },
      { id: 'append', code: 'scores.Add(100);' },
      { id: 'foreach', code: 'foreach (int score in scores) {' },
      { id: 'output', code: '    Console.WriteLine(score);' },
      { id: 'loop-close', code: '}' },
    ],
    correctOrder: ['list', 'append', 'foreach', 'output', 'loop-close'],
    explanation:
      'The list is created before Add changes it, and foreach then displays each element inside its body.',
    reference: csharpCollectionsReference,
  },
  {
    id: 'csharp-basics.sequence.person-object',
    topicId: 'csharp-basics',
    kind: 'sequence',
    prompt: 'Arrange a top-level program that constructs a Person and displays its property.',
    instruction:
      'Use the class from top-level code, then place its declaration after the statements.',
    items: [
      { id: 'create', code: 'Person person = new Person("Ada");' },
      { id: 'output', code: 'Console.WriteLine(person.Name);' },
      { id: 'class', code: 'public class Person {' },
      { id: 'property', code: '    public string Name { get; set; }' },
      { id: 'constructor', code: '    public Person(string name) {' },
      { id: 'assign', code: '        Name = name;' },
      { id: 'constructor-close', code: '    }' },
      { id: 'class-close', code: '}' },
    ],
    correctOrder: [
      'create',
      'output',
      'class',
      'property',
      'constructor',
      'assign',
      'constructor-close',
      'class-close',
    ],
    explanation:
      'Top-level statements create and use the object before the type declaration, while the constructor initializes the Name property.',
    reference: csharpClassesReference,
  },
] as const satisfies readonly SequenceQuestion[]
