import type { TextBlankQuestion } from '../../../types'
import {
  csharpBuiltInTypesReference,
  csharpCollectionsReference,
  csharpConsoleReference,
  csharpIterationReference,
  csharpMethodsReference,
  csharpOperatorsReference,
  csharpPropertiesReference,
  csharpSelectionReference,
  csharpTypesReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'csharp-basics.text.write-line',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the call that writes a greeting followed by a newline.',
    instruction: 'Type the missing Console method name.',
    template: { before: 'Console.', after: '("Hello!");' },
    canonicalAnswer: 'WriteLine',
    acceptedAnswers: ['WriteLine'],
    explanation:
      'Console.WriteLine writes its argument to standard output and then terminates the current line.',
    reference: csharpConsoleReference,
  },
  {
    id: 'csharp-basics.text.string-type',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the declaration with the built-in C# type for text.',
    instruction: 'Type the missing type keyword.',
    template: { before: '', after: ' name = "Ada";' },
    canonicalAnswer: 'string',
    acceptedAnswers: ['string'],
    explanation:
      'The string keyword is the C# alias for System.String and represents a sequence of characters.',
    reference: csharpBuiltInTypesReference,
  },
  {
    id: 'csharp-basics.text.inferred-type',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the declaration so the compiler infers the local variable type.',
    instruction: 'Type the missing contextual keyword.',
    template: { before: '', after: ' count = scores.Count;' },
    canonicalAnswer: 'var',
    acceptedAnswers: ['var'],
    explanation:
      'var tells the compiler to determine count’s static type from the initializer expression.',
    reference: csharpTypesReference,
  },
  {
    id: 'csharp-basics.text.interpolated-string',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the string so the value of name is inserted between the braces.',
    instruction: 'Type the missing one-character interpolation prefix.',
    template: { before: 'string greeting = ', after: '"Hello, {name}!";' },
    canonicalAnswer: '$',
    acceptedAnswers: ['$'],
    explanation:
      'The $ prefix creates an interpolated string whose braced expressions are evaluated and formatted.',
    reference: csharpBuiltInTypesReference,
  },
  {
    id: 'csharp-basics.text.remainder',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the expression that finds the remainder after dividing value by 2.',
    instruction: 'Type the missing arithmetic operator.',
    template: { before: 'int remainder = value ', after: ' 2;' },
    canonicalAnswer: '%',
    acceptedAnswers: ['%'],
    explanation: 'The remainder operator % returns the remainder produced by integer division.',
    reference: csharpOperatorsReference,
  },
  {
    id: 'csharp-basics.text.else-branch',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the fallback branch of the conditional.',
    instruction: 'Type the missing C# keyword.',
    template: {
      before: 'if (ready) {\n    Start();\n} ',
      after: ' {\n    Wait();\n}',
    },
    canonicalAnswer: 'else',
    acceptedAnswers: ['else'],
    explanation:
      'An else branch runs when the Boolean condition belonging to the preceding if is false.',
    reference: csharpSelectionReference,
  },
  {
    id: 'csharp-basics.text.continue-loop',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the statement that skips negative values and starts the next iteration.',
    instruction: 'Type the missing loop-control keyword.',
    template: {
      before: 'foreach (int value in values) {\n    if (value < 0) {\n        ',
      after: ';\n    }\n    Process(value);\n}',
    },
    canonicalAnswer: 'continue',
    acceptedAnswers: ['continue'],
    explanation:
      'continue stops the current loop iteration and proceeds with the next available element.',
    reference: csharpIterationReference,
  },
  {
    id: 'csharp-basics.text.return-result',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the method so it sends the sum back to its caller.',
    instruction: 'Type the missing C# keyword.',
    template: {
      before: 'static int Add(int left, int right) {\n    ',
      after: ' left + right;\n}',
    },
    canonicalAnswer: 'return',
    acceptedAnswers: ['return'],
    explanation:
      'return ends the method call and supplies the following expression as the method result.',
    reference: csharpMethodsReference,
  },
  {
    id: 'csharp-basics.text.list-add',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the call that appends 95 to scores.',
    instruction: 'Type the missing List<T> method name with its C# capitalization.',
    template: { before: 'scores.', after: '(95);' },
    canonicalAnswer: 'Add',
    acceptedAnswers: ['Add'],
    explanation: 'The Add method places one new element at the end of a List<T>.',
    reference: csharpCollectionsReference,
  },
  {
    id: 'csharp-basics.text.property-getter',
    topicId: 'csharp-basics',
    kind: 'text-blank',
    prompt: 'Complete the auto-property with the accessor that reads its stored value.',
    instruction: 'Type the missing accessor keyword.',
    template: { before: 'public string Name { ', after: '; set; } = "";' },
    canonicalAnswer: 'get',
    acceptedAnswers: ['get'],
    explanation:
      'A get accessor makes the property value readable by code that can access the property.',
    reference: csharpPropertiesReference,
  },
] as const satisfies readonly TextBlankQuestion[]
