import type { DragBlankQuestion } from '../../../types'
import {
  testingLibraryAsyncReference,
  testingLibraryJestDomReference,
  testingLibraryQueriesReference,
  testingLibraryReactReference,
  testingLibraryUserEventReference,
  vitestConfigReference,
  vitestMockFunctionsReference,
  vitestWritingTestsReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'vitest.drag-describe-group',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Group the related Counter tests under one suite.',
    instruction: 'Choose the Vitest function that creates a test suite.',
    template: { before: '', after: "('Counter', () => {\n  // tests\n})" },
    options: [
      { id: 'describe', label: 'describe', code: 'describe' },
      { id: 'expect', label: 'expect', code: 'expect' },
      { id: 'render', label: 'render', code: 'render' },
      { id: 'before', label: 'beforeEach', code: 'beforeEach' },
    ],
    correctOptionId: 'describe',
    explanation:
      'describe creates a named suite for related tests and gives their lifecycle hooks a clear shared scope.',
    reference: vitestWritingTestsReference,
  },
  {
    id: 'vitest.drag-render-function',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Mount the LoginForm component for this test.',
    instruction: 'Choose the React Testing Library rendering function.',
    template: { before: '', after: '(<LoginForm />)' },
    options: [
      { id: 'render', label: 'render', code: 'render' },
      { id: 'screen', label: 'screen', code: 'screen' },
      { id: 'expect', label: 'expect', code: 'expect' },
      { id: 'describe', label: 'describe', code: 'describe' },
    ],
    correctOptionId: 'render',
    explanation:
      'render mounts a React element into the test DOM and returns helpers for the created container and rerendering.',
    reference: testingLibraryReactReference,
  },
  {
    id: 'vitest.drag-label-query',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Find the email input through its associated label.',
    instruction: 'Choose the Testing Library query for labeled form controls.',
    template: { before: 'screen.', after: "('Email')" },
    options: [
      { id: 'label', label: 'getByLabelText', code: 'getByLabelText' },
      { id: 'role', label: 'getByRole', code: 'getByRole' },
      { id: 'test-id', label: 'getByTestId', code: 'getByTestId' },
      { id: 'display', label: 'getByDisplayValue', code: 'getByDisplayValue' },
    ],
    correctOptionId: 'label',
    explanation:
      'getByLabelText finds a form control through the label a user reads, keeping the query aligned with the form’s accessible contract.',
    reference: testingLibraryQueriesReference,
  },
  {
    id: 'vitest.drag-absence-query',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Check that no alert is currently rendered without throwing when it is absent.',
    instruction: 'Choose the role query intended for a possible missing element.',
    template: { before: 'expect(screen.', after: "('alert')).not.toBeInTheDocument()" },
    options: [
      { id: 'query', label: 'queryByRole', code: 'queryByRole' },
      { id: 'get', label: 'getByRole', code: 'getByRole' },
      { id: 'find', label: 'findByRole', code: 'findByRole' },
      { id: 'all', label: 'getAllByRole', code: 'getAllByRole' },
    ],
    correctOptionId: 'query',
    explanation:
      'queryByRole returns null when no match exists, allowing a negative DOM assertion instead of throwing before the matcher runs.',
    reference: testingLibraryQueriesReference,
  },
  {
    id: 'vitest.drag-user-click',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Activate the Submit button through the configured user session.',
    instruction: 'Choose the user-event interaction method.',
    template: { before: 'await user.', after: "(screen.getByRole('button', { name: 'Submit' }))" },
    options: [
      { id: 'click', label: 'click', code: 'click' },
      { id: 'press', label: 'press', code: 'press' },
      { id: 'submit', label: 'submit', code: 'submit' },
      { id: 'trigger', label: 'trigger', code: 'trigger' },
    ],
    correctOptionId: 'click',
    explanation:
      'user.click models the pointer and mouse events involved in activating the selected button and returns a promise to await.',
    reference: testingLibraryUserEventReference,
  },
  {
    id: 'vitest.drag-wait-for',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Retry the callback assertion until the asynchronous save invokes its mock.',
    instruction: 'Choose the Testing Library asynchronous retry helper.',
    template: { before: 'await ', after: '(() => expect(save).toHaveBeenCalled())' },
    options: [
      { id: 'wait-for', label: 'waitFor', code: 'waitFor' },
      { id: 'find', label: 'findBy', code: 'findBy' },
      { id: 'sleep', label: 'sleep', code: 'sleep' },
      { id: 'retry', label: 'retry', code: 'retry' },
    ],
    correctOptionId: 'wait-for',
    explanation:
      'waitFor repeatedly runs the callback until it stops throwing or reaches its timeout, fitting an eventually satisfied mock assertion.',
    reference: testingLibraryAsyncReference,
  },
  {
    id: 'vitest.drag-text-matcher',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Assert that the status contains the rendered text Profile saved.',
    instruction: 'Choose the jest-dom matcher for element text content.',
    template: { before: 'expect(status).', after: "('Profile saved')" },
    options: [
      { id: 'text-content', label: 'toHaveTextContent', code: 'toHaveTextContent' },
      { id: 'text', label: 'toBeText', code: 'toBeText' },
      { id: 'contain', label: 'toContain', code: 'toContain' },
      { id: 'value', label: 'toHaveValue', code: 'toHaveValue' },
    ],
    correctOptionId: 'text-content',
    explanation:
      'toHaveTextContent checks the text rendered by a DOM node and communicates the intended component output directly.',
    reference: testingLibraryJestDomReference,
  },
  {
    id: 'vitest.drag-spy-method',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Observe localStorage.getItem while preserving access to the existing method.',
    instruction: 'Choose the vi API that spies on an object method.',
    template: { before: 'const getItem = vi.', after: "(Storage.prototype, 'getItem')" },
    options: [
      { id: 'spy', label: 'spyOn', code: 'spyOn' },
      { id: 'fn', label: 'fn', code: 'fn' },
      { id: 'mock', label: 'mock', code: 'mock' },
      { id: 'stub', label: 'stub', code: 'stub' },
    ],
    correctOptionId: 'spy',
    explanation:
      'vi.spyOn wraps the selected prototype method so the test can inspect calls or replace the implementation and restore it afterward.',
    reference: vitestMockFunctionsReference,
  },
  {
    id: 'vitest.drag-mock-result',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Make the async loadProfile mock resolve with Ada’s profile.',
    instruction: 'Choose the mock method that supplies a resolved promise value.',
    template: { before: 'loadProfile.', after: "({ name: 'Ada' })" },
    options: [
      { id: 'resolved', label: 'mockResolvedValue', code: 'mockResolvedValue' },
      { id: 'return', label: 'mockReturnValue', code: 'mockReturnValue' },
      { id: 'rejected', label: 'mockRejectedValue', code: 'mockRejectedValue' },
      { id: 'implementation', label: 'mockImplementationOnce', code: 'mockImplementationOnce' },
    ],
    correctOptionId: 'resolved',
    explanation:
      'mockResolvedValue configures the mock to return a promise fulfilled with the supplied profile object.',
    reference: vitestMockFunctionsReference,
  },
  {
    id: 'vitest.drag-setup-files',
    topicId: 'vitest',
    kind: 'drag-blank',
    prompt: 'Configure the file that installs DOM matchers before tests execute.',
    instruction: 'Choose the Vitest configuration property for shared setup modules.',
    template: { before: 'test: { ', after: ": ['./src/test/setup.ts'] }" },
    options: [
      { id: 'setup', label: 'setupFiles', code: 'setupFiles' },
      { id: 'include', label: 'include', code: 'include' },
      { id: 'environment', label: 'environment', code: 'environment' },
      { id: 'reporters', label: 'reporters', code: 'reporters' },
    ],
    correctOptionId: 'setup',
    explanation:
      'setupFiles lists modules that Vitest evaluates before each test file, making it suitable for installing matchers and common cleanup.',
    reference: vitestConfigReference,
  },
] as const satisfies readonly DragBlankQuestion[]
