import type { TextBlankQuestion } from '../../../types'
import {
  testingLibraryAsyncReference,
  testingLibraryJestDomReference,
  testingLibraryQueriesReference,
  testingLibraryReactReference,
  testingLibraryUserEventReference,
  vitestEnvironmentReference,
  vitestMockFunctionsReference,
  vitestWritingTestsReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'vitest.text-expect-import',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Complete the Vitest import so the test can make assertions.',
    instruction: 'Type the missing named export.',
    template: { before: 'import { describe, it, ', after: " } from 'vitest'" },
    canonicalAnswer: 'expect',
    acceptedAnswers: ['expect'],
    explanation:
      'expect wraps the received value and exposes matchers that compare it with the behavior the test requires.',
    reference: vitestWritingTestsReference,
  },
  {
    id: 'vitest.text-test-declaration',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Declare an individual test for the Counter component.',
    instruction: 'Type the short Vitest alias that begins the test declaration.',
    template: { before: '', after: "('increments the count', () => {\n  // test\n})" },
    canonicalAnswer: 'it',
    acceptedAnswers: ['it'],
    explanation:
      'it is an alias of test and declares one named scenario whose callback contains the test steps and assertions.',
    reference: vitestWritingTestsReference,
  },
  {
    id: 'vitest.text-render-component',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Mount the Counter component into the test document.',
    instruction: 'Type the React Testing Library function that renders a React element.',
    template: { before: '', after: '(<Counter />)' },
    canonicalAnswer: 'render',
    acceptedAnswers: ['render'],
    explanation:
      'render mounts the supplied React element into a DOM container so Testing Library queries can inspect its output.',
    reference: testingLibraryReactReference,
  },
  {
    id: 'vitest.text-role-query',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Find the Save control by its button role and accessible name.',
    instruction: 'Type the missing screen query method.',
    template: { before: 'screen.', after: "('button', { name: 'Save' })" },
    canonicalAnswer: 'getByRole',
    acceptedAnswers: ['getByRole'],
    explanation:
      'getByRole locates an element through its semantic role and accessible name, matching how a user identifies the control.',
    reference: testingLibraryQueriesReference,
  },
  {
    id: 'vitest.text-user-setup',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Create a user-event session for this component test.',
    instruction: 'Type the missing userEvent method.',
    template: { before: 'const user = userEvent.', after: '()' },
    canonicalAnswer: 'setup',
    acceptedAnswers: ['setup'],
    explanation:
      'userEvent.setup creates a session whose asynchronous methods model interactions such as clicking, typing, and keyboard input.',
    reference: testingLibraryUserEventReference,
  },
  {
    id: 'vitest.text-await-click',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Wait for the user interaction to finish before asserting the result.',
    instruction: 'Type the missing JavaScript keyword.',
    template: { before: '', after: " user.click(screen.getByRole('button', { name: 'Add' }))" },
    canonicalAnswer: 'await',
    acceptedAnswers: ['await'],
    explanation:
      'user-event interactions return promises, so await lets their event sequence and related React updates complete before the assertion.',
    reference: testingLibraryUserEventReference,
  },
  {
    id: 'vitest.text-find-async-status',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Wait for a status element that is rendered after an asynchronous save.',
    instruction: 'Type the missing asynchronous screen query method.',
    template: { before: 'const status = await screen.', after: "('status')" },
    canonicalAnswer: 'findByRole',
    acceptedAnswers: ['findByRole'],
    explanation:
      'findByRole retries the semantic role query until the element appears or the asynchronous query timeout is reached.',
    reference: testingLibraryAsyncReference,
  },
  {
    id: 'vitest.text-document-matcher',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Assert that the heading is attached to the rendered document.',
    instruction: 'Type the missing jest-dom matcher without parentheses.',
    template: { before: "expect(screen.getByRole('heading')).", after: '()' },
    canonicalAnswer: 'toBeInTheDocument',
    acceptedAnswers: ['toBeInTheDocument'],
    explanation:
      'toBeInTheDocument states that the queried DOM node belongs to the current document, making the presence assertion explicit.',
    reference: testingLibraryJestDomReference,
  },
  {
    id: 'vitest.text-mock-function',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Create a callback test double that records how it is called.',
    instruction: 'Type the missing vi method.',
    template: { before: 'const onSave = vi.', after: '()' },
    canonicalAnswer: 'fn',
    acceptedAnswers: ['fn'],
    explanation:
      'vi.fn creates a callable mock function with recorded calls, arguments, results, and configurable behavior.',
    reference: vitestMockFunctionsReference,
  },
  {
    id: 'vitest.text-jsdom-environment',
    topicId: 'vitest',
    kind: 'text-blank',
    prompt: 'Configure the browser-like environment used by React DOM tests.',
    instruction: 'Type the missing environment name without quotes.',
    template: { before: "test: { environment: '", after: "' }" },
    canonicalAnswer: 'jsdom',
    acceptedAnswers: ['jsdom'],
    explanation:
      'The jsdom environment supplies browser-like globals such as window and document while the component tests run in Node.',
    reference: vitestEnvironmentReference,
  },
] as const satisfies readonly TextBlankQuestion[]
