import type { DragBlankQuestion } from '../../../types'
import {
  boxPlotReference,
  dataQualityReference,
  histogramReference,
  locationMeasuresReference,
  scatterPlotReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'data-analysis.drag.unique-key',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Choose the field that should uniquely identify an order before duplicate checks.',
    instruction: 'Select the most suitable record key.',
    template: { before: 'unique order key = ', after: '' },
    options: [
      { id: 'order-id', label: 'order_id', code: 'order_id' },
      { id: 'region', label: 'region', code: 'region' },
      { id: 'status', label: 'status', code: 'status' },
      { id: 'amount', label: 'amount', code: 'amount' },
    ],
    correctOptionId: 'order-id',
    explanation:
      'An order identifier is intended to distinguish individual orders. Region, status, and amount normally repeat across many legitimate records.',
    reference: dataQualityReference,
  },
  {
    id: 'data-analysis.drag.missing-marker',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Preserve an unknown satisfaction score without pretending it is a measured zero.',
    instruction: 'Choose the value that explicitly represents missing data.',
    template: { before: 'satisfaction_score = ', after: '' },
    options: [
      { id: 'missing', label: 'NA', code: 'NA' },
      { id: 'zero', label: '0', code: '0' },
      { id: 'average', label: 'overall average', code: 'overall_average' },
      { id: 'maximum', label: 'maximum score', code: 'maximum_score' },
    ],
    correctOptionId: 'missing',
    explanation:
      'An explicit missing marker preserves the distinction between “unknown” and an actual score of zero until a documented treatment is chosen.',
    reference: dataQualityReference,
  },
  {
    id: 'data-analysis.drag.robust-center',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Choose a center for a strongly skewed income distribution with a few extreme values.',
    instruction: 'Select the measure that is resistant to extremes.',
    template: { before: 'reported typical income = ', after: '(income)' },
    options: [
      { id: 'median', label: 'median', code: 'median' },
      { id: 'mean', label: 'mean', code: 'mean' },
      { id: 'maximum', label: 'maximum', code: 'maximum' },
      { id: 'range', label: 'range', code: 'range' },
    ],
    correctOptionId: 'median',
    explanation:
      'The median depends on ordered position rather than the size of extreme values, so it often represents the center of a skewed distribution more usefully.',
    reference: locationMeasuresReference,
  },
  {
    id: 'data-analysis.drag.percentage-formula',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Complete the formula for the percentage of late orders.',
    instruction: 'Choose the expression with the relevant part and whole.',
    template: { before: 'late percentage = ', after: ' × 100' },
    options: [
      { id: 'part-whole', label: 'late_orders / all_orders', code: 'late_orders / all_orders' },
      { id: 'whole-part', label: 'all_orders / late_orders', code: 'all_orders / late_orders' },
      { id: 'difference', label: 'all_orders − late_orders', code: 'all_orders - late_orders' },
      { id: 'sum', label: 'all_orders + late_orders', code: 'all_orders + late_orders' },
    ],
    correctOptionId: 'part-whole',
    explanation:
      'A percentage divides the part of interest by its relevant whole. Late orders are the part and all eligible orders form the denominator.',
    reference: dataQualityReference,
  },
  {
    id: 'data-analysis.drag.bar-chart',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Choose a chart for comparing ticket counts across named categories.',
    instruction: 'Select the chart designed for discrete category comparisons.',
    template: { before: 'category counts → ', after: '' },
    options: [
      { id: 'bar', label: 'bar chart', code: 'bar chart' },
      { id: 'histogram', label: 'histogram', code: 'histogram' },
      { id: 'scatter', label: 'scatter plot', code: 'scatter plot' },
      { id: 'box', label: 'box plot', code: 'box plot' },
    ],
    correctOptionId: 'bar',
    explanation:
      'A bar chart gives each category a separate bar, making category counts or percentages straightforward to compare.',
    reference: histogramReference,
  },
  {
    id: 'data-analysis.drag.histogram',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Choose a chart for examining the distribution of 2,000 delivery durations.',
    instruction: 'Select the chart that groups one numeric variable into intervals.',
    template: { before: 'delivery-duration distribution → ', after: '' },
    options: [
      { id: 'histogram', label: 'histogram', code: 'histogram' },
      { id: 'bar', label: 'bar chart of row IDs', code: 'bar chart' },
      { id: 'pie', label: 'pie chart', code: 'pie chart' },
      { id: 'map', label: 'map', code: 'map' },
    ],
    correctOptionId: 'histogram',
    explanation:
      'A histogram bins quantitative observations and shows their frequency, revealing distribution shape, location, spread, and possible outliers.',
    reference: histogramReference,
  },
  {
    id: 'data-analysis.drag.box-plot',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Compare the median and spread of response times across four teams.',
    instruction: 'Choose the compact distribution comparison.',
    template: { before: 'response time by team → ', after: '' },
    options: [
      { id: 'box', label: 'side-by-side box plots', code: 'side-by-side box plots' },
      { id: 'pie', label: 'four pie charts', code: 'four pie charts' },
      { id: 'single-mean', label: 'one overall mean', code: 'one overall mean' },
      { id: 'table-id', label: 'a table of record IDs', code: 'a table of record IDs' },
    ],
    correctOptionId: 'box',
    explanation:
      'Side-by-side box plots expose each group’s median, quartiles, spread, and flagged extremes on a shared scale.',
    reference: boxPlotReference,
  },
  {
    id: 'data-analysis.drag.scatter-plot',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Examine whether advertising spend and weekly sales move together.',
    instruction: 'Choose the chart for paired quantitative variables.',
    template: { before: 'advertising spend versus sales → ', after: '' },
    options: [
      { id: 'scatter', label: 'scatter plot', code: 'scatter plot' },
      { id: 'histogram', label: 'one histogram', code: 'histogram' },
      { id: 'bar', label: 'bar chart of sales categories', code: 'bar chart' },
      { id: 'pie', label: 'pie chart', code: 'pie chart' },
    ],
    correctOptionId: 'scatter',
    explanation:
      'A scatter plot places each paired observation by its two quantitative values, revealing direction, form, strength, clusters, and unusual points.',
    reference: scatterPlotReference,
  },
  {
    id: 'data-analysis.drag.rate-denominator',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Complete the defect rate so two factories of different sizes can be compared fairly.',
    instruction: 'Choose the relevant denominator.',
    template: { before: 'defect rate = defective_units / ', after: '' },
    options: [
      { id: 'inspected', label: 'all_inspected_units', code: 'all_inspected_units' },
      { id: 'defective', label: 'defective_units', code: 'defective_units' },
      { id: 'factories', label: 'number_of_factories', code: 'number_of_factories' },
      { id: 'days', label: 'days_in_month', code: 'days_in_month' },
    ],
    correctOptionId: 'inspected',
    explanation:
      'All inspected units are the population at risk of being counted as defective, so that denominator normalizes for different production volumes.',
    reference: dataQualityReference,
  },
  {
    id: 'data-analysis.drag.causation-caveat',
    topicId: 'data-analysis',
    kind: 'drag-blank',
    prompt: 'Complete the responsible interpretation of a strong correlation.',
    instruction: 'Choose the conclusion supported by association alone.',
    template: { before: 'The variables are associated, but ', after: '.' },
    options: [
      { id: 'not-cause', label: 'this alone does not establish causation' },
      { id: 'proves', label: 'this proves the first variable causes the second' },
      { id: 'no-confounding', label: 'confounding is impossible' },
      { id: 'perfect', label: 'every future value can be predicted perfectly' },
    ],
    correctOptionId: 'not-cause',
    explanation:
      'Association can arise from confounding, selection, reverse direction, or chance. A scatter plot or correlation cannot by itself establish cause and effect.',
    reference: scatterPlotReference,
  },
] as const satisfies readonly DragBlankQuestion[]
