import type { TextBlankQuestion } from '../../../types'
import {
  exploratoryDataAnalysisReference,
  histogramReference,
  locationMeasuresReference,
  variabilityReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'data-analysis.text.mean',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Calculate the arithmetic mean of 4, 6, and 8.',
    instruction: 'Type the missing numeric result.',
    template: { before: 'mean = (4 + 6 + 8) / 3 = ', after: '' },
    canonicalAnswer: '6',
    acceptedAnswers: ['6', '6.0'],
    explanation:
      'The three values sum to 18, and dividing that total by the count of three observations gives a mean of 6.',
    reference: locationMeasuresReference,
  },
  {
    id: 'data-analysis.text.median',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Calculate the median of the ordered values 2, 4, 9, and 100.',
    instruction: 'Type the missing numeric result.',
    template: { before: 'median = (4 + 9) / 2 = ', after: '' },
    canonicalAnswer: '6.5',
    acceptedAnswers: ['6.5', '6,5'],
    explanation:
      'With four ordered observations, the median is the mean of the two middle values. Averaging 4 and 9 gives 6.5.',
    reference: locationMeasuresReference,
  },
  {
    id: 'data-analysis.text.range',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Calculate the range of 4, 7, and 15.',
    instruction: 'Type the difference between the maximum and minimum.',
    template: { before: 'range = 15 − 4 = ', after: '' },
    canonicalAnswer: '11',
    acceptedAnswers: ['11', '11.0'],
    explanation:
      'Range is the maximum value minus the minimum value, so this dataset has a range of 15 minus 4, or 11.',
    reference: variabilityReference,
  },
  {
    id: 'data-analysis.text.iqr',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Calculate the interquartile range when Q1 is 10 and Q3 is 18.',
    instruction: 'Type the missing numeric result.',
    template: { before: 'IQR = Q3 − Q1 = 18 − 10 = ', after: '' },
    canonicalAnswer: '8',
    acceptedAnswers: ['8', '8.0'],
    explanation:
      'The interquartile range subtracts the lower quartile from the upper quartile and describes the spread of the middle 50% of observations.',
    reference: variabilityReference,
  },
  {
    id: 'data-analysis.text.percentage',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Thirty of 120 orders arrived late. Complete the late-order percentage.',
    instruction: 'Type the result as a percentage.',
    template: { before: '(30 / 120) × 100 = ', after: '' },
    canonicalAnswer: '25%',
    acceptedAnswers: ['25%', '25 %', '25 percent'],
    explanation:
      'The part-to-whole ratio is 30 divided by 120, or 0.25. Multiplying by 100 expresses that ratio as 25%.',
    reference: exploratoryDataAnalysisReference,
  },
  {
    id: 'data-analysis.text.observations',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Name what rows usually represent in a tidy analysis table.',
    instruction: 'Type the missing plural term.',
    template: { before: 'Rows represent ', after: '; columns represent variables.' },
    canonicalAnswer: 'observations',
    acceptedAnswers: ['observations', 'records', 'cases'],
    explanation:
      'A common tabular structure assigns each row to one observed unit or record and each column to one variable measured about it.',
    reference: exploratoryDataAnalysisReference,
  },
  {
    id: 'data-analysis.text.variables',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Name what columns usually represent in a tidy analysis table.',
    instruction: 'Type the missing plural term.',
    template: { before: 'Rows represent observations; columns represent ', after: '.' },
    canonicalAnswer: 'variables',
    acceptedAnswers: ['variables', 'fields', 'features'],
    explanation:
      'Each column normally holds one consistently defined variable, such as region, order date, or delivery duration, across observations.',
    reference: exploratoryDataAnalysisReference,
  },
  {
    id: 'data-analysis.text.histogram-bins',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Name the numeric intervals used to group values in a histogram.',
    instruction: 'Type the missing plural term.',
    template: { before: 'A histogram groups numeric values into ', after: '.' },
    canonicalAnswer: 'bins',
    acceptedAnswers: ['bins', 'classes', 'intervals'],
    explanation:
      'A histogram divides a quantitative range into bins and counts how many observations fall within each interval.',
    reference: histogramReference,
  },
  {
    id: 'data-analysis.text.time-axis',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Complete the usual horizontal axis for a line chart showing a weekly trend.',
    instruction: 'Type the missing concept.',
    template: { before: 'horizontal axis = ', after: '; vertical axis = weekly value' },
    canonicalAnswer: 'time',
    acceptedAnswers: ['time', 'date', 'week', 'weeks'],
    explanation:
      'Placing ordered time on the horizontal axis lets the connected values show how the measure changes from one period to the next.',
    reference: exploratoryDataAnalysisReference,
  },
  {
    id: 'data-analysis.text.sample',
    topicId: 'data-analysis',
    kind: 'text-blank',
    prompt: 'Name an observed subset used to learn about a larger population.',
    instruction: 'Type the statistical term.',
    template: { before: 'Observed subset = ', after: '' },
    canonicalAnswer: 'sample',
    acceptedAnswers: ['sample', 'a sample'],
    explanation:
      'A sample contains the units actually observed, while the population is the full group about which the analysis aims to draw conclusions.',
    reference: exploratoryDataAnalysisReference,
  },
] as const satisfies readonly TextBlankQuestion[]
