import type { DragBlankQuestion } from '../../../types'
import {
  cppExpressionsReference,
  cppFunctionsReference,
  cppInitializationReference,
  cppIostreamReference,
  cppStatementsReference,
  cppVectorReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'cpp-basics.drag.include-iostream',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Include the header needed for std::cout.',
    instruction: 'Select the correct standard-library header.',
    template: { before: '#include ', after: '\n\nint main() { /* ... */ }' },
    options: [
      { id: 'iostream', label: '<iostream>', code: '<iostream>' },
      { id: 'vector', label: '<vector>', code: '<vector>' },
      { id: 'string', label: '<string>', code: '<string>' },
      { id: 'cmath', label: '<cmath>', code: '<cmath>' },
    ],
    correctOptionId: 'iostream',
    explanation:
      'The iostream header supplies the declarations for standard stream objects such as std::cout.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.drag.namespace-qualifier',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Qualify cout as a name from the standard-library namespace.',
    instruction: 'Select the missing namespace qualifier.',
    template: { before: '', after: 'cout << "Ready\\n";' },
    options: [
      { id: 'std', label: 'std::', code: 'std::' },
      { id: 'cpp', label: 'cpp::', code: 'cpp::' },
      { id: 'global', label: '::', code: '::' },
      { id: 'std-dot', label: 'std.', code: 'std.' },
    ],
    correctOptionId: 'std',
    explanation:
      'Standard-library names are in namespace std, and :: is the C++ scope-resolution operator.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.drag.brace-initialization',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Initialize attempts to 3 with brace initialization.',
    instruction: 'Select the syntax that supplies a braced initializer.',
    template: { before: 'int attempts', after: ';' },
    options: [
      { id: 'braces', label: '{3}', code: '{3}' },
      { id: 'brackets', label: '[3]', code: '[3]' },
      { id: 'colon', label: ': 3', code: ': 3' },
      { id: 'arrow', label: '-> 3', code: '-> 3' },
    ],
    correctOptionId: 'braces',
    explanation:
      'A braced initializer follows the declared name directly, so int attempts{3}; initializes the object to 3.',
    reference: cppInitializationReference,
  },
  {
    id: 'cpp-basics.drag.const-declaration',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Declare maxScore as an integer that cannot be assigned a new value.',
    instruction: 'Select the qualifier that makes the initialized object non-modifiable.',
    template: { before: '', after: ' int maxScore{100};' },
    options: [
      { id: 'const', label: 'const', code: 'const' },
      { id: 'auto', label: 'auto', code: 'auto' },
      { id: 'void', label: 'void', code: 'void' },
      { id: 'static-cast', label: 'static_cast', code: 'static_cast' },
    ],
    correctOptionId: 'const',
    explanation:
      'const qualifies maxScore so it must be initialized and cannot later be modified through assignment.',
    reference: cppInitializationReference,
  },
  {
    id: 'cpp-basics.drag.floating-division',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Convert total before division so average keeps a fractional part.',
    instruction: 'Select the explicit conversion expression.',
    template: { before: 'double average{', after: ' / count};' },
    options: [
      {
        id: 'static-cast',
        label: 'static_cast<double>(total)',
        code: 'static_cast<double>(total)',
      },
      { id: 'unchanged', label: 'total', code: 'total' },
      { id: 'boolean', label: 'static_cast<bool>(total)', code: 'static_cast<bool>(total)' },
      { id: 'size', label: 'sizeof(total)', code: 'sizeof(total)' },
    ],
    correctOptionId: 'static-cast',
    explanation:
      'Converting total to double makes the division floating-point instead of integer division.',
    reference: cppExpressionsReference,
  },
  {
    id: 'cpp-basics.drag.logical-or',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Allow access when the user is an owner or an administrator.',
    instruction: 'Select the logical operator that accepts either true operand.',
    template: { before: 'if (isOwner ', after: ' isAdmin) {\n    allow();\n}' },
    options: [
      { id: 'or', label: '||', code: '||' },
      { id: 'and', label: '&&', code: '&&' },
      { id: 'equal', label: '==', code: '==' },
      { id: 'not', label: '!', code: '!' },
    ],
    correctOptionId: 'or',
    explanation: 'Logical OR uses || and produces true when at least one of its operands is true.',
    reference: cppExpressionsReference,
  },
  {
    id: 'cpp-basics.drag.switch-break',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Stop this matching switch case before the next case runs.',
    instruction: 'Select the statement that exits the switch.',
    template: {
      before: "case 'q':\n    running = false;\n    ",
      after: ';\ndefault:\n    showHelp();',
    },
    options: [
      { id: 'break', label: 'break', code: 'break' },
      { id: 'continue', label: 'continue', code: 'continue' },
      { id: 'case', label: 'case', code: 'case' },
      { id: 'else', label: 'else', code: 'else' },
    ],
    correctOptionId: 'break',
    explanation:
      'break exits the nearest switch so execution does not fall through into the default case.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.drag.range-for',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Visit every integer stored in values.',
    instruction: 'Select the range-based for loop header.',
    template: { before: '', after: ' {\n    std::cout << value;\n}' },
    options: [
      { id: 'range', label: 'for (int value : values)', code: 'for (int value : values)' },
      { id: 'while', label: 'while (int value : values)', code: 'while (int value : values)' },
      { id: 'if', label: 'if (int value : values)', code: 'if (int value : values)' },
      { id: 'index', label: 'for (values : int value)', code: 'for (values : int value)' },
    ],
    correctOptionId: 'range',
    explanation:
      'A range-based for loop places the element declaration before a colon and the range expression after it.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.drag.function-result',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Declare doubleValue as a function that produces an integer.',
    instruction: 'Select the return type that matches the returned expression.',
    template: { before: '', after: ' doubleValue(int value) {\n    return value * 2;\n}' },
    options: [
      { id: 'int', label: 'int', code: 'int' },
      { id: 'void', label: 'void', code: 'void' },
      { id: 'return', label: 'return', code: 'return' },
      { id: 'auto-parameter', label: 'int()', code: 'int()' },
    ],
    correctOptionId: 'int',
    explanation:
      'The return type appears before the function name, and int matches the integer expression returned by the body.',
    reference: cppFunctionsReference,
  },
  {
    id: 'cpp-basics.drag.vector-type',
    topicId: 'cpp-basics',
    kind: 'drag-blank',
    prompt: 'Declare a resizable standard-library sequence of integers.',
    instruction: 'Select the type that stores the initializer elements.',
    template: { before: '', after: ' scores{80, 90, 100};' },
    options: [
      { id: 'vector', label: 'std::vector<int>', code: 'std::vector<int>' },
      { id: 'string', label: 'std::string', code: 'std::string' },
      { id: 'int', label: 'int', code: 'int' },
      { id: 'bool-vector', label: 'std::vector<bool>', code: 'std::vector<bool>' },
    ],
    correctOptionId: 'vector',
    explanation:
      'std::vector<int> is a resizable standard-library sequence whose elements have type int.',
    reference: cppVectorReference,
  },
] as const satisfies readonly DragBlankQuestion[]
