import type { SequenceQuestion } from '../../../types'
import {
  cppExpressionsReference,
  cppFunctionsReference,
  cppIostreamReference,
  cppStatementsReference,
  cppStringReference,
  cppVectorReference,
} from './shared'

export const sequenceQuestions = [
  {
    id: 'cpp-basics.sequence.hello-program',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a complete program that writes a greeting.',
    instruction: 'Include the stream header, define main, produce output, and finish the function.',
    items: [
      { id: 'include', code: '#include <iostream>' },
      { id: 'main', code: 'int main() {' },
      { id: 'output', code: '    std::cout << "Hello\\n";' },
      { id: 'return', code: '    return 0;' },
      { id: 'close', code: '}' },
    ],
    correctOrder: ['include', 'main', 'output', 'return', 'close'],
    explanation:
      'The header precedes its stream use, output and return belong inside main, and the closing brace ends the function.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.sequence.read-and-write',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a program that reads an age and writes it back.',
    instruction: 'Declare the input destination before extraction, then display the stored value.',
    items: [
      { id: 'include', code: '#include <iostream>' },
      { id: 'main', code: 'int main() {' },
      { id: 'age', code: '    int age{};' },
      { id: 'input', code: '    std::cin >> age;' },
      { id: 'output', code: "    std::cout << age << '\\n';" },
      { id: 'return', code: '    return 0;' },
      { id: 'close', code: '}' },
    ],
    correctOrder: ['include', 'main', 'age', 'input', 'output', 'return', 'close'],
    explanation:
      'The stream declarations are included first, age is initialized before input stores into it, and output reads it before main returns.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.sequence.floating-average',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange the declarations that calculate and display a fractional average.',
    instruction: 'Prepare both integer operands, convert before division, and then use the result.',
    items: [
      { id: 'total', code: 'int total{7};' },
      { id: 'count', code: 'int count{2};' },
      { id: 'average', code: 'double average{static_cast<double>(total) / count};' },
      { id: 'output', code: 'std::cout << average;' },
    ],
    correctOrder: ['total', 'count', 'average', 'output'],
    acceptedOrders: [['count', 'total', 'average', 'output']],
    explanation:
      'total and count may be declared in either order, but both must exist before average is calculated and then displayed.',
    reference: cppExpressionsReference,
  },
  {
    id: 'cpp-basics.sequence.if-else-grade',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange the conditional that assigns and displays a grade.',
    instruction: 'Declare the values, complete both branches, and display the assigned grade.',
    items: [
      { id: 'score', code: 'int score{85};' },
      { id: 'grade', code: 'char grade{};' },
      { id: 'if', code: 'if (score >= 90) {' },
      { id: 'a', code: "    grade = 'A';" },
      { id: 'else', code: '} else {' },
      { id: 'b', code: "    grade = 'B';" },
      { id: 'close', code: '}' },
      { id: 'output', code: 'std::cout << grade;' },
    ],
    correctOrder: ['score', 'grade', 'if', 'a', 'else', 'b', 'close', 'output'],
    acceptedOrders: [['grade', 'score', 'if', 'a', 'else', 'b', 'close', 'output']],
    explanation:
      'The independent declarations come first, each assignment stays in its branch, and grade is displayed after the conditional assigns it.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.sequence.for-total',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange the loop that totals the integers from 1 through 3.',
    instruction: 'Initialize the accumulator, complete the loop, and then display the total.',
    items: [
      { id: 'total', code: 'int total{};' },
      { id: 'for', code: 'for (int value{1}; value <= 3; ++value) {' },
      { id: 'add', code: '    total += value;' },
      { id: 'close', code: '}' },
      { id: 'output', code: 'std::cout << total;' },
    ],
    correctOrder: ['total', 'for', 'add', 'close', 'output'],
    explanation:
      'The accumulator exists before the loop, the addition belongs in the loop body, and output occurs after all iterations finish.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.sequence.while-countdown',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a while loop that displays 3, 2, and 1.',
    instruction: 'Initialize the counter, test it, display it, and decrease it each iteration.',
    items: [
      { id: 'counter', code: 'int count{3};' },
      { id: 'while', code: 'while (count > 0) {' },
      { id: 'output', code: "    std::cout << count << '\\n';" },
      { id: 'decrement', code: '    --count;' },
      { id: 'close', code: '}' },
    ],
    correctOrder: ['counter', 'while', 'output', 'decrement', 'close'],
    explanation:
      'count is initialized before the condition, and each iteration prints the current value before decrementing toward loop termination.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.sequence.function-call',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a square function and a main function that calls it.',
    instruction: 'Define the helper before using its returned value in main.',
    items: [
      { id: 'function', code: 'int square(int value) {' },
      { id: 'function-return', code: '    return value * value;' },
      { id: 'function-close', code: '}' },
      { id: 'main', code: 'int main() {' },
      { id: 'call', code: '    int result{square(4)};' },
      { id: 'main-return', code: '    return result == 16 ? 0 : 1;' },
      { id: 'main-close', code: '}' },
    ],
    correctOrder: [
      'function',
      'function-return',
      'function-close',
      'main',
      'call',
      'main-return',
      'main-close',
    ],
    explanation:
      'The square definition is complete before main calls it, and main evaluates the stored result before returning its status.',
    reference: cppFunctionsReference,
  },
  {
    id: 'cpp-basics.sequence.function-declaration',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a declaration, call, and later definition of add.',
    instruction: 'Introduce the function before main uses it, then provide its body.',
    items: [
      { id: 'declaration', code: 'int add(int left, int right);' },
      { id: 'main', code: 'int main() {' },
      { id: 'call', code: '    int total{add(2, 3)};' },
      { id: 'main-return', code: '    return total == 5 ? 0 : 1;' },
      { id: 'main-close', code: '}' },
      { id: 'definition', code: 'int add(int left, int right) {' },
      { id: 'function-return', code: '    return left + right;' },
      { id: 'function-close', code: '}' },
    ],
    correctOrder: [
      'declaration',
      'main',
      'call',
      'main-return',
      'main-close',
      'definition',
      'function-return',
      'function-close',
    ],
    explanation:
      'The declaration makes add known to main; after main closes, the matching definition supplies the function body.',
    reference: cppFunctionsReference,
  },
  {
    id: 'cpp-basics.sequence.vector-loop',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a program that appends to a vector and displays every value.',
    instruction: 'Include dependencies, prepare the vector, append, and then iterate over it.',
    items: [
      { id: 'vector-include', code: '#include <vector>' },
      { id: 'iostream-include', code: '#include <iostream>' },
      { id: 'main', code: 'int main() {' },
      { id: 'values', code: '    std::vector<int> values{1, 2};' },
      { id: 'append', code: '    values.push_back(3);' },
      { id: 'for', code: '    for (int value : values) {' },
      { id: 'output', code: "        std::cout << value << '\\n';" },
      { id: 'for-close', code: '    }' },
      { id: 'main-close', code: '}' },
    ],
    correctOrder: [
      'vector-include',
      'iostream-include',
      'main',
      'values',
      'append',
      'for',
      'output',
      'for-close',
      'main-close',
    ],
    requiredOrderPairs: [
      ['vector-include', 'main'],
      ['iostream-include', 'main'],
      ['main', 'values'],
      ['values', 'append'],
      ['append', 'for'],
      ['for', 'output'],
      ['output', 'for-close'],
      ['for-close', 'main-close'],
    ],
    explanation:
      'The headers may appear in either order, but the vector must exist before append and the loop must enclose output before main closes.',
    reference: cppVectorReference,
  },
  {
    id: 'cpp-basics.sequence.string-greeting',
    topicId: 'cpp-basics',
    kind: 'sequence',
    prompt: 'Arrange a program that builds and displays a string greeting.',
    instruction: 'Include dependencies, prepare both strings, append the name, and produce output.',
    items: [
      { id: 'string-include', code: '#include <string>' },
      { id: 'iostream-include', code: '#include <iostream>' },
      { id: 'main', code: 'int main() {' },
      { id: 'name', code: '    std::string name{"Ada"};' },
      { id: 'greeting', code: '    std::string greeting{"Hello, "};' },
      { id: 'append', code: '    greeting += name;' },
      { id: 'output', code: "    std::cout << greeting << '\\n';" },
      { id: 'close', code: '}' },
    ],
    correctOrder: [
      'string-include',
      'iostream-include',
      'main',
      'name',
      'greeting',
      'append',
      'output',
      'close',
    ],
    requiredOrderPairs: [
      ['string-include', 'main'],
      ['iostream-include', 'main'],
      ['main', 'name'],
      ['main', 'greeting'],
      ['name', 'append'],
      ['greeting', 'append'],
      ['append', 'output'],
      ['output', 'close'],
    ],
    explanation:
      'Header and independent string declaration order may vary, but both strings must exist before concatenation and output follows it.',
    reference: cppStringReference,
  },
] as const satisfies readonly SequenceQuestion[]
