import type { TextBlankQuestion } from '../../../types'
import {
  cppExpressionsReference,
  cppFunctionsReference,
  cppInitializationReference,
  cppIostreamReference,
  cppStatementsReference,
  cppVectorReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'cpp-basics.text.iostream-header',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the directive that includes the standard stream declarations.',
    instruction: 'Type the missing header name without angle brackets.',
    template: { before: '#include <', after: '>' },
    canonicalAnswer: 'iostream',
    acceptedAnswers: ['iostream'],
    explanation:
      'The iostream header declares standard stream objects including std::cout and std::cin.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.text.standard-output',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the statement that writes the score to standard output.',
    instruction: 'Type the fully qualified output stream name.',
    template: { before: '', after: " << score << '\\n';" },
    canonicalAnswer: 'std::cout',
    acceptedAnswers: ['std::cout'],
    explanation:
      'std::cout names the standard character output stream, which accepts inserted values through <<.',
    reference: cppIostreamReference,
  },
  {
    id: 'cpp-basics.text.floating-type',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the declaration with a common floating-point type.',
    instruction: 'Type the missing C++ type.',
    template: { before: '', after: ' ratio{0.5};' },
    canonicalAnswer: 'double',
    acceptedAnswers: ['double'],
    explanation:
      'double is a fundamental floating-point type commonly used for values with fractional parts.',
    reference: cppInitializationReference,
  },
  {
    id: 'cpp-basics.text.const-value',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the declaration so maxAttempts cannot be assigned a new value.',
    instruction: 'Type the missing type qualifier.',
    template: { before: '', after: ' int maxAttempts{3};' },
    canonicalAnswer: 'const',
    acceptedAnswers: ['const'],
    explanation:
      'The const qualifier makes maxAttempts non-modifiable after its required initialization.',
    reference: cppInitializationReference,
  },
  {
    id: 'cpp-basics.text.inferred-type',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the declaration so the compiler infers the variable type.',
    instruction: 'Type the missing placeholder type.',
    template: { before: '', after: ' count = scores.size();' },
    canonicalAnswer: 'auto',
    acceptedAnswers: ['auto'],
    explanation:
      'auto tells the compiler to infer count’s type from the initializer expression scores.size().',
    reference: cppInitializationReference,
  },
  {
    id: 'cpp-basics.text.remainder',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the expression that calculates the remainder after dividing value by 2.',
    instruction: 'Type the missing arithmetic operator.',
    template: { before: 'int remainder{value ', after: ' 2};' },
    canonicalAnswer: '%',
    acceptedAnswers: ['%'],
    explanation: 'The remainder operator % produces the remainder from integer division.',
    reference: cppExpressionsReference,
  },
  {
    id: 'cpp-basics.text.else-branch',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the fallback branch of the conditional.',
    instruction: 'Type the missing C++ keyword.',
    template: {
      before: 'if (ready) {\n    start();\n} ',
      after: ' {\n    wait();\n}',
    },
    canonicalAnswer: 'else',
    acceptedAnswers: ['else'],
    explanation:
      'An else branch runs when the condition belonging to its preceding if statement is false.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.text.continue-loop',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the statement that skips negative values and starts the next iteration.',
    instruction: 'Type the missing loop-control keyword.',
    template: {
      before: 'for (int value : values) {\n    if (value < 0) {\n        ',
      after: ';\n    }\n    process(value);\n}',
    },
    canonicalAnswer: 'continue',
    acceptedAnswers: ['continue'],
    explanation:
      'continue stops the current loop iteration and resumes with the next element in the range.',
    reference: cppStatementsReference,
  },
  {
    id: 'cpp-basics.text.return-result',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the function so it sends the sum back to its caller.',
    instruction: 'Type the missing C++ keyword.',
    template: { before: 'int add(int left, int right) {\n    ', after: ' left + right;\n}' },
    canonicalAnswer: 'return',
    acceptedAnswers: ['return'],
    explanation:
      'return ends the function call and supplies the following expression as the function result.',
    reference: cppFunctionsReference,
  },
  {
    id: 'cpp-basics.text.vector-append',
    topicId: 'cpp-basics',
    kind: 'text-blank',
    prompt: 'Complete the call that adds 95 to the end of scores.',
    instruction: 'Type the missing std::vector member-function name.',
    template: { before: 'scores.', after: '(95);' },
    canonicalAnswer: 'push_back',
    acceptedAnswers: ['push_back'],
    explanation: 'The push_back member function appends one element to the end of a std::vector.',
    reference: cppVectorReference,
  },
] as const satisfies readonly TextBlankQuestion[]
