import type { DragBlankQuestion } from '../../../types'
import {
  typescriptBasicsReference,
  typescriptEverydayTypesReference,
  typescriptGenericsReference,
  typescriptNarrowingReference,
  typescriptObjectTypesReference,
  typescriptStrictReference,
  typescriptTypeofReference,
  typescriptUtilityTypesReference,
} from './shared'

export const dragBlankQuestions = [
  {
    id: 'typescript.drag-unknown-value',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Type an external value safely before its shape has been checked.',
    instruction: 'Choose the type that requires narrowing before use.',
    template: { before: 'let payload: ', after: ' = JSON.parse(raw)' },
    options: [
      { id: 'unknown', label: 'unknown', code: 'unknown' },
      { id: 'any', label: 'any', code: 'any' },
      { id: 'object', label: 'object', code: 'object' },
      { id: 'never', label: 'never', code: 'never' },
    ],
    correctOptionId: 'unknown',
    explanation:
      'unknown can hold the parsed value while preventing unchecked property access until code narrows or validates its shape.',
    reference: typescriptBasicsReference,
  },
  {
    id: 'typescript.drag-literal-union',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Allow only the two documented status strings.',
    instruction: 'Choose the precise literal union.',
    template: { before: 'type Status = ', after: '' },
    options: [
      { id: 'literal-union', label: '"idle" | "done"', code: '"idle" | "done"' },
      { id: 'string', label: 'string', code: 'string' },
      { id: 'array', label: 'string[]', code: 'string[]' },
      { id: 'intersection', label: '"idle" & "done"', code: '"idle" & "done"' },
    ],
    correctOptionId: 'literal-union',
    explanation:
      'The union of two string literal types accepts exactly "idle" or "done" instead of every possible string.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.drag-array-narrowing',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Narrow value from string | string[] before joining array elements.',
    instruction: 'Choose the runtime guard that detects arrays.',
    template: { before: 'if (', after: '(value)) {\n  return value.join(", ")\n}' },
    options: [
      { id: 'is-array', label: 'Array.isArray', code: 'Array.isArray' },
      { id: 'typeof-array', label: 'typeof Array', code: 'typeof Array' },
      { id: 'array-of', label: 'Array.of', code: 'Array.of' },
      { id: 'instance', label: 'Array.instance', code: 'Array.instance' },
    ],
    correctOptionId: 'is-array',
    explanation:
      'Array.isArray performs the runtime check and TypeScript recognizes it as a guard that narrows value to an array.',
    reference: typescriptNarrowingReference,
  },
  {
    id: 'typescript.drag-interface-extension',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Extend the User interface with administrator permissions.',
    instruction: 'Choose the interface inheritance keyword.',
    template: { before: 'interface Admin ', after: ' User {\n  permissions: string[]\n}' },
    options: [
      { id: 'extends', label: 'extends', code: 'extends' },
      { id: 'implements', label: 'implements', code: 'implements' },
      { id: 'inherits', label: 'inherits', code: 'inherits' },
      { id: 'from', label: 'from', code: 'from' },
    ],
    correctOptionId: 'extends',
    explanation:
      'An interface uses extends to include the base interface’s members and add new requirements of its own.',
    reference: typescriptObjectTypesReference,
  },
  {
    id: 'typescript.drag-intersection-type',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Combine User and Timestamped into one type that requires both shapes.',
    instruction: 'Choose the intersection type operator.',
    template: { before: 'type AuditedUser = User ', after: ' Timestamped' },
    options: [
      { id: 'intersection', label: '&', code: '&' },
      { id: 'union', label: '|', code: '|' },
      { id: 'optional', label: '?', code: '?' },
      { id: 'arrow', label: '=>', code: '=>' },
    ],
    correctOptionId: 'intersection',
    explanation:
      'The ampersand forms an intersection, so an AuditedUser must satisfy the required members of both source types.',
    reference: typescriptObjectTypesReference,
  },
  {
    id: 'typescript.drag-optional-parameter',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Allow callers to omit the title argument.',
    instruction: 'Choose the optional-parameter marker.',
    template: { before: 'function greet(name: string, title', after: ': string) {\n  // ...\n}' },
    options: [
      { id: 'question', label: '?', code: '?' },
      { id: 'bang', label: '!', code: '!' },
      { id: 'pipe', label: '|', code: '|' },
      { id: 'ampersand', label: '&', code: '&' },
    ],
    correctOptionId: 'question',
    explanation:
      'A question mark after a parameter name makes that parameter optional, allowing the function to be called without title.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.drag-generic-constraint',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Constrain T so the function may safely read value.length.',
    instruction: 'Choose the keyword that introduces a generic constraint.',
    template: {
      before: 'function lengthOf<T ',
      after: ' { length: number }>(value: T) {\n  return value.length\n}',
    },
    options: [
      { id: 'extends', label: 'extends', code: 'extends' },
      { id: 'implements', label: 'implements', code: 'implements' },
      { id: 'keyof', label: 'keyof', code: 'keyof' },
      { id: 'typeof', label: 'typeof', code: 'typeof' },
    ],
    correctOptionId: 'extends',
    explanation:
      'A generic extends constraint requires every inferred T to provide a numeric length property before the function uses it.',
    reference: typescriptGenericsReference,
  },
  {
    id: 'typescript.drag-typeof-query',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Derive Options from the static type of the defaults value.',
    instruction: 'Choose the type-query operator.',
    template: { before: 'const defaults = { retries: 3 }\ntype Options = ', after: ' defaults' },
    options: [
      { id: 'typeof', label: 'typeof', code: 'typeof' },
      { id: 'keyof', label: 'keyof', code: 'keyof' },
      { id: 'instanceof', label: 'instanceof', code: 'instanceof' },
      { id: 'infer', label: 'infer', code: 'infer' },
    ],
    correctOptionId: 'typeof',
    explanation:
      'In a type position, typeof captures the static shape of defaults so the declaration does not have to repeat it.',
    reference: typescriptTypeofReference,
  },
  {
    id: 'typescript.drag-pick-utility',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Create UserPreview with only the id and name properties from User.',
    instruction: 'Choose the utility type that selects named properties.',
    template: { before: 'type UserPreview = ', after: '<User, "id" | "name">' },
    options: [
      { id: 'pick', label: 'Pick', code: 'Pick' },
      { id: 'omit', label: 'Omit', code: 'Omit' },
      { id: 'partial', label: 'Partial', code: 'Partial' },
      { id: 'record', label: 'Record', code: 'Record' },
    ],
    correctOptionId: 'pick',
    explanation:
      'Pick constructs a new object type from the listed keys of User, leaving all unselected properties out.',
    reference: typescriptUtilityTypesReference,
  },
  {
    id: 'typescript.drag-strict-config',
    topicId: 'typescript',
    kind: 'drag-blank',
    prompt: 'Enable the full family of strict type-checking options.',
    instruction: 'Choose the boolean compiler-option value.',
    template: { before: '{\n  "compilerOptions": {\n    "strict": ', after: '\n  }\n}' },
    options: [
      { id: 'true', label: 'true', code: 'true' },
      { id: 'false', label: 'false', code: 'false' },
      { id: 'auto', label: '"auto"', code: '"auto"' },
      { id: 'all', label: '"all"', code: '"all"' },
    ],
    correctOptionId: 'true',
    explanation:
      'Setting strict to the boolean value true enables TypeScript’s strict family of type-checking rules for the project.',
    reference: typescriptStrictReference,
  },
] as const satisfies readonly DragBlankQuestion[]
