import type { SequenceQuestion } from '../../../types'
import {
  typescriptEverydayTypesReference,
  typescriptFunctionsReference,
  typescriptGenericsReference,
  typescriptKeyofReference,
  typescriptModulesReference,
  typescriptNarrowingReference,
  typescriptObjectTypesReference,
  typescriptUtilityTypesReference,
} from './shared'

export const sequenceQuestions = [
  {
    id: 'typescript.sequence.typed-function-call',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange the typed greeting function and the code that uses its result.',
    instruction: 'Complete the function before calling it, then display the returned message.',
    items: [
      { id: 'function', code: 'function greet(name: string): string {' },
      { id: 'return', code: '  return `Hello, ${name}`' },
      { id: 'close', code: '}' },
      { id: 'call', code: 'const message = greet("Ada")' },
      { id: 'print', code: 'console.log(message)' },
    ],
    correctOrder: ['function', 'return', 'close', 'call', 'print'],
    explanation:
      'The return belongs inside the function, the declaration closes before its call, and message must be assigned before it is logged.',
    reference: typescriptFunctionsReference,
  },
  {
    id: 'typescript.sequence.array-transformation',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange the program that doubles a typed array and displays the result.',
    instruction: 'Define the source before deriving and printing the transformed array.',
    items: [
      { id: 'source', code: 'const values: number[] = [1, 2, 3]' },
      { id: 'map', code: 'const doubled = values.map((value) => value * 2)' },
      { id: 'print', code: 'console.log(doubled)' },
    ],
    correctOrder: ['source', 'map', 'print'],
    explanation:
      'values must exist before map reads it, and doubled must be assigned before the final console call can display it.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.sequence.union-narrowing',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange the function that formats a string-or-number union safely.',
    instruction: 'Narrow the union inside the function before using member-specific methods.',
    items: [
      { id: 'function', code: 'function format(value: string | number): string {' },
      { id: 'guard', code: '  if (typeof value === "string") {' },
      { id: 'string-return', code: '    return value.toUpperCase()' },
      { id: 'guard-close', code: '  }' },
      { id: 'number-return', code: '  return value.toFixed(2)' },
      { id: 'function-close', code: '}' },
    ],
    correctOrder: [
      'function',
      'guard',
      'string-return',
      'guard-close',
      'number-return',
      'function-close',
    ],
    explanation:
      'The typeof branch handles strings and returns early, leaving value narrowed to number for the final numeric return.',
    reference: typescriptNarrowingReference,
  },
  {
    id: 'typescript.sequence.discriminated-union',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a discriminated result type and a function that reads its successful value.',
    instruction: 'Declare the union, then narrow it inside the function before reading data.',
    items: [
      {
        id: 'type',
        code: 'type Result = { ok: true; data: string } | { ok: false; error: string }',
      },
      { id: 'function', code: 'function message(result: Result): string {' },
      { id: 'guard', code: '  if (result.ok) {' },
      { id: 'data', code: '    return result.data' },
      { id: 'guard-close', code: '  }' },
      { id: 'error', code: '  return result.error' },
      { id: 'function-close', code: '}' },
    ],
    correctOrder: ['type', 'function', 'guard', 'data', 'guard-close', 'error', 'function-close'],
    explanation:
      'Result must be declared before use, and checking its literal ok property narrows each return path to the matching union member.',
    reference: typescriptNarrowingReference,
  },
  {
    id: 'typescript.sequence.interface-value',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange the User interface, a matching value, and code that reads it.',
    instruction: 'Complete the object contract before creating and using the typed value.',
    items: [
      { id: 'interface', code: 'interface User {' },
      { id: 'id', code: '  readonly id: number' },
      { id: 'name', code: '  name: string' },
      { id: 'interface-close', code: '}' },
      { id: 'value', code: 'const user: User = { id: 1, name: "Ada" }' },
      { id: 'print', code: 'console.log(user.name)' },
    ],
    correctOrder: ['interface', 'id', 'name', 'interface-close', 'value', 'print'],
    acceptedOrders: [['interface', 'name', 'id', 'interface-close', 'value', 'print']],
    explanation:
      'The properties may appear in either order inside the interface, which must close before User annotates the value that is later read.',
    reference: typescriptObjectTypesReference,
  },
  {
    id: 'typescript.sequence.generic-first',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a generic first function and a call that uses its inferred result.',
    instruction:
      'Define the generic relationship before calling the function and checking the result.',
    items: [
      { id: 'function', code: 'function first<T>(items: T[]): T | undefined {' },
      { id: 'return', code: '  return items[0]' },
      { id: 'function-close', code: '}' },
      { id: 'call', code: 'const firstName = first(["Ada", "Lin"])' },
      { id: 'guard', code: 'if (firstName !== undefined) {' },
      { id: 'print', code: '  console.log(firstName.toUpperCase())' },
      { id: 'guard-close', code: '}' },
    ],
    correctOrder: ['function', 'return', 'function-close', 'call', 'guard', 'print', 'guard-close'],
    explanation:
      'The generic function is defined first, its possibly undefined result is assigned, and the guard narrows that result before string use.',
    reference: typescriptGenericsReference,
  },
  {
    id: 'typescript.sequence.key-safe-getter',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a key-safe property getter and a valid call.',
    instruction:
      'Define the constrained generic before creating the object and reading one of its keys.',
    items: [
      { id: 'function', code: 'function get<T, K extends keyof T>(object: T, key: K): T[K] {' },
      { id: 'return', code: '  return object[key]' },
      { id: 'function-close', code: '}' },
      { id: 'value', code: 'const user = { id: 1, name: "Ada" }' },
      { id: 'call', code: 'const name = get(user, "name")' },
      { id: 'print', code: 'console.log(name.toUpperCase())' },
    ],
    correctOrder: ['function', 'return', 'function-close', 'value', 'call', 'print'],
    acceptedOrders: [['value', 'function', 'return', 'function-close', 'call', 'print']],
    explanation:
      'The object and function may be prepared in either order, but both must exist before the constrained call returns name for string use.',
    reference: typescriptKeyofReference,
  },
  {
    id: 'typescript.sequence.partial-update',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a User type, a partial update type, and an update value.',
    instruction: 'Declare the base shape before deriving and using its optional-property version.',
    items: [
      { id: 'user', code: 'type User = { id: number; name: string }' },
      { id: 'update', code: 'type UserUpdate = Partial<User>' },
      { id: 'changes', code: 'const changes: UserUpdate = { name: "Grace" }' },
      { id: 'print', code: 'console.log(changes.name)' },
    ],
    correctOrder: ['user', 'update', 'changes', 'print'],
    explanation:
      'Partial needs the User declaration, changes uses the derived alias, and the value must be initialized before its property is logged.',
    reference: typescriptUtilityTypesReference,
  },
  {
    id: 'typescript.sequence.module-import',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a module import and the code that uses its exported function.',
    instruction: 'Import the function, prepare its arguments, call it, and display the result.',
    items: [
      { id: 'import', code: 'import { add } from "./math.js"' },
      { id: 'left', code: 'const left: number = 2' },
      { id: 'right', code: 'const right: number = 3' },
      { id: 'call', code: 'const total = add(left, right)' },
      { id: 'print', code: 'console.log(total)' },
    ],
    correctOrder: ['import', 'left', 'right', 'call', 'print'],
    acceptedOrders: [
      ['import', 'right', 'left', 'call', 'print'],
      ['left', 'import', 'right', 'call', 'print'],
      ['right', 'import', 'left', 'call', 'print'],
      ['left', 'right', 'import', 'call', 'print'],
      ['right', 'left', 'import', 'call', 'print'],
    ],
    explanation:
      'The import and independent arguments may be prepared in any order, but all three must precede the call and total must precede output.',
    reference: typescriptModulesReference,
  },
  {
    id: 'typescript.sequence.strict-null-check',
    topicId: 'typescript',
    kind: 'sequence',
    prompt: 'Arrange a lookup and guard that safely uses a possibly missing user.',
    instruction:
      'Define the collection, perform the lookup, and narrow its result before property access.',
    items: [
      { id: 'users', code: 'const users = [{ id: 1, name: "Ada" }]' },
      { id: 'lookup', code: 'const user = users.find((candidate) => candidate.id === 1)' },
      { id: 'guard', code: 'if (user !== undefined) {' },
      { id: 'print', code: '  console.log(user.name.toUpperCase())' },
      { id: 'guard-close', code: '}' },
    ],
    correctOrder: ['users', 'lookup', 'guard', 'print', 'guard-close'],
    explanation:
      'The array must exist before find runs, and checking the possibly undefined result narrows user before its name property is accessed.',
    reference: typescriptNarrowingReference,
  },
] as const satisfies readonly SequenceQuestion[]
