import type { TextBlankQuestion } from '../../../types'
import {
  typescriptEverydayTypesReference,
  typescriptFunctionsReference,
  typescriptGenericsReference,
  typescriptKeyofReference,
  typescriptModulesReference,
  typescriptNarrowingReference,
  typescriptObjectTypesReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'typescript.text-string-annotation',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the annotation so name accepts string values.',
    instruction: 'Type the missing TypeScript primitive type.',
    template: { before: 'let name: ', after: ' = "Ada"' },
    canonicalAnswer: 'string',
    acceptedAnswers: ['string'],
    explanation:
      'The lowercase string type describes JavaScript string primitives and belongs after the colon in this annotation.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.text-number-array',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the element type for this array of numbers.',
    instruction: 'Type the missing primitive type before the array brackets.',
    template: { before: 'const scores: ', after: '[] = [10, 20, 30]' },
    canonicalAnswer: 'number',
    acceptedAnswers: ['number'],
    explanation:
      'Appending square brackets to number creates number[], the type of an array whose elements are numbers.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.text-union-operator',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the type so id may be either a string or a number.',
    instruction: 'Type the missing union operator.',
    template: { before: 'let id: string ', after: ' number' },
    canonicalAnswer: '|',
    acceptedAnswers: ['|'],
    explanation:
      'The vertical bar forms a union type, allowing id to hold a value compatible with either listed member.',
    reference: typescriptEverydayTypesReference,
  },
  {
    id: 'typescript.text-typeof-guard',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the typeof check that narrows value to string.',
    instruction: 'Type the missing runtime typeof result without quotes.',
    template: { before: 'if (typeof value === "', after: '") {\n  value.toUpperCase()\n}' },
    canonicalAnswer: 'string',
    acceptedAnswers: ['string'],
    explanation:
      'At runtime typeof returns the text "string" for string primitives, and TypeScript uses this guard to narrow the branch.',
    reference: typescriptNarrowingReference,
  },
  {
    id: 'typescript.text-optional-property',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Make bio optional in this interface.',
    instruction: 'Type the missing optional-property marker.',
    template: { before: 'interface Profile {\n  bio', after: ': string\n}' },
    canonicalAnswer: '?',
    acceptedAnswers: ['?'],
    explanation:
      'A question mark after the property name marks bio as optional, so compatible objects may omit it.',
    reference: typescriptObjectTypesReference,
  },
  {
    id: 'typescript.text-readonly-property',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Prevent assignment to id through a User value.',
    instruction: 'Type the missing property modifier.',
    template: { before: 'interface User {\n  ', after: ' id: number\n}' },
    canonicalAnswer: 'readonly',
    acceptedAnswers: ['readonly'],
    explanation:
      'The readonly modifier prevents code from assigning a new value through the id property after initialization.',
    reference: typescriptObjectTypesReference,
  },
  {
    id: 'typescript.text-return-type',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the explicit return type for this numeric function.',
    instruction: 'Type the missing TypeScript primitive type.',
    template: { before: 'function double(value: number): ', after: ' {\n  return value * 2\n}' },
    canonicalAnswer: 'number',
    acceptedAnswers: ['number'],
    explanation:
      'A return annotation follows the parameter list, and number matches the result of multiplying two numeric values.',
    reference: typescriptFunctionsReference,
  },
  {
    id: 'typescript.text-generic-parameter',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Complete the generic identity function so one type connects its input and output.',
    instruction: 'Type the conventional single-letter type parameter.',
    template: { before: 'function identity<', after: '>(value: T): T {\n  return value\n}' },
    canonicalAnswer: 'T',
    acceptedAnswers: ['T'],
    explanation:
      'Declaring T in angle brackets makes it a type parameter that the value parameter and return annotation can share.',
    reference: typescriptGenericsReference,
  },
  {
    id: 'typescript.text-keyof-operator',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Restrict K to the known property names of T.',
    instruction: 'Type the missing type operator.',
    template: {
      before: 'function get<T, K extends ',
      after: ' T>(object: T, key: K) {\n  return object[key]\n}',
    },
    canonicalAnswer: 'keyof',
    acceptedAnswers: ['keyof'],
    explanation:
      'keyof T produces the permitted property keys, so the constraint rejects names that do not exist on T.',
    reference: typescriptKeyofReference,
  },
  {
    id: 'typescript.text-type-only-import',
    topicId: 'typescript',
    kind: 'text-blank',
    prompt: 'Mark this import as usable only in type positions.',
    instruction: 'Type the missing import modifier.',
    template: { before: 'import ', after: ' { User } from "./user.js"' },
    canonicalAnswer: 'type',
    acceptedAnswers: ['type'],
    explanation:
      'The type modifier makes the import’s purpose explicit and allows it to be erased completely from emitted JavaScript.',
    reference: typescriptModulesReference,
  },
] as const satisfies readonly TextBlankQuestion[]
