import type { TextBlankQuestion } from '../../../types'
import {
  jmeterComponentReference,
  jmeterDashboardReference,
  jmeterFunctionsReference,
  jmeterGettingStartedReference,
  jmeterTestPlanReference,
} from './shared'

export const textBlankQuestions = [
  {
    id: 'jmeter.text-thread-group',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Name the element that configures threads, ramp-up, loops, and duration.',
    instruction: 'Type the missing JMeter element name.',
    template: { before: 'Test Plan\n└─ ', after: '\n   └─ HTTP Request' },
    canonicalAnswer: 'Thread Group',
    acceptedAnswers: ['Thread Group', 'thread group'],
    explanation:
      'The Thread Group is the starting point for samplers and controllers and defines the virtual-user workload schedule.',
    reference: jmeterTestPlanReference,
  },
  {
    id: 'jmeter.text-http-sampler',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Complete the minimal web plan with the sampler that sends an HTTP call.',
    instruction: 'Type the missing JMeter sampler name.',
    template: { before: 'Test Plan\n└─ Thread Group\n   └─ ', after: '' },
    canonicalAnswer: 'HTTP Request',
    acceptedAnswers: ['HTTP Request', 'http request'],
    explanation:
      'The HTTP Request sampler sends an HTTP or HTTPS request and records the result as a sample for JMeter to process.',
    reference: jmeterComponentReference,
  },
  {
    id: 'jmeter.text-variable',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Reference the username variable supplied by CSV Data Set Config.',
    instruction: 'Type only the missing variable name.',
    template: { before: 'POST body: { "username": "${', after: '}" }' },
    canonicalAnswer: 'username',
    acceptedAnswers: ['username'],
    explanation:
      'JMeter resolves dollar-brace expressions at runtime, so ${username} inserts the current value assigned to the username variable.',
    reference: jmeterFunctionsReference,
  },
  {
    id: 'jmeter.text-json-extractor',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Name the post-processor used to capture a token from a JSON response.',
    instruction: 'Type the missing JMeter component name.',
    template: { before: 'Login HTTP Request\n└─ ', after: '\n   Variable: token' },
    canonicalAnswer: 'JSON Extractor',
    acceptedAnswers: ['JSON Extractor', 'json extractor'],
    explanation:
      'A JSON Extractor runs after its sampler, evaluates a JSONPath expression, and stores the selected response value in a variable.',
    reference: jmeterComponentReference,
  },
  {
    id: 'jmeter.text-response-assertion',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Name the assertion that can check whether a response contains expected text.',
    instruction: 'Type the missing assertion component name.',
    template: { before: 'HTTP Request\n└─ ', after: '\n   Pattern: "orderId"' },
    canonicalAnswer: 'Response Assertion',
    acceptedAnswers: ['Response Assertion', 'response assertion'],
    explanation:
      'Response Assertion tests response fields against configured patterns and marks the sample failed when the expectation is not met.',
    reference: jmeterComponentReference,
  },
  {
    id: 'jmeter.text-cli-mode',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Complete the command-line option that runs JMeter without the GUI.',
    instruction: 'Type the missing option including its hyphen.',
    template: { before: 'jmeter ', after: ' -t checkout.jmx -l results.jtl' },
    canonicalAnswer: '-n',
    acceptedAnswers: ['-n'],
    explanation:
      'The -n option selects CLI mode, which avoids the graphical interface overhead during an actual load test.',
    reference: jmeterGettingStartedReference,
  },
  {
    id: 'jmeter.text-test-plan-option',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Complete the option that selects the JMX test plan to execute.',
    instruction: 'Type the missing option including its hyphen.',
    template: { before: 'jmeter -n ', after: ' checkout.jmx -l results.jtl' },
    canonicalAnswer: '-t',
    acceptedAnswers: ['-t'],
    explanation:
      'The -t option is followed by the path to the JMX file containing the JMeter test plan for the run.',
    reference: jmeterGettingStartedReference,
  },
  {
    id: 'jmeter.text-results-option',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Complete the option that writes sample results to a JTL file.',
    instruction: 'Type the missing option including its hyphen.',
    template: { before: 'jmeter -n -t checkout.jmx ', after: ' results.jtl' },
    canonicalAnswer: '-l',
    acceptedAnswers: ['-l'],
    explanation:
      'The -l option names the sample-results log that can later be processed by JMeter reporting and analysis tools.',
    reference: jmeterGettingStartedReference,
  },
  {
    id: 'jmeter.text-property-function',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Complete the JMeter function that reads the threads property with a default of 10.',
    instruction: 'Type only the missing function name.',
    template: { before: '${', after: '(threads,10)}' },
    canonicalAnswer: '__P',
    acceptedAnswers: ['__P', '__p'],
    explanation:
      'The __P function reads a JMeter property and returns the supplied default when that property was not defined for the run.',
    reference: jmeterFunctionsReference,
  },
  {
    id: 'jmeter.text-dashboard-option',
    topicId: 'jmeter',
    kind: 'text-blank',
    prompt: 'Add the option that generates the HTML dashboard after the load test.',
    instruction: 'Type the missing option including its hyphen.',
    template: {
      before: 'jmeter -n -t checkout.jmx -l results.jtl ',
      after: ' -o report',
    },
    canonicalAnswer: '-e',
    acceptedAnswers: ['-e'],
    explanation:
      'The -e option generates the dashboard after the run, while -o selects the empty directory that receives the report.',
    reference: jmeterDashboardReference,
  },
] as const satisfies readonly TextBlankQuestion[]
