/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as TopicsTopicIdQuizRouteImport } from './routes/topics_.$topicId.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdQuizRoute = TopicsTopicIdQuizRouteImport.update({
  id: '/topics_/$topicId/quiz',
  path: '/topics/$topicId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/$topicId/quiz': typeof TopicsTopicIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/$topicId/quiz': typeof TopicsTopicIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics_/$topicId/quiz': typeof TopicsTopicIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topics/$topicId' | '/topics/$topicId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topics/$topicId' | '/topics/$topicId/quiz'
  id: '__root__' | '/' | '/topics/$topicId' | '/topics_/$topicId/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TopicsTopicIdQuizRoute: typeof TopicsTopicIdQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics_/$topicId/quiz': {
      id: '/topics_/$topicId/quiz'
      path: '/topics/$topicId/quiz'
      fullPath: '/topics/$topicId/quiz'
      preLoaderRoute: typeof TopicsTopicIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TopicsTopicIdQuizRoute: TopicsTopicIdQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
