import type { SequenceQuestion } from '../../../types'
import {
  accessibilityEvaluationReference,
  ariaDialogReference,
  axeReference,
  lighthouseReference,
  waveReference,
  wcagKeyboardTrapReference,
} from './shared'

export const sequenceQuestions = [
  {
    id: 'accessibility-testing.sequence.layered-review',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Arrange this layered page review from scope to verification.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'scope', code: 'Define representative pages, flows, states, and target standard' },
      { id: 'render', code: 'Open a representative page in the state being tested' },
      { id: 'scan', code: 'Run automated accessibility scans' },
      { id: 'triage', code: 'Inspect and triage every result in context' },
      { id: 'manual', code: 'Complete keyboard, visual, and assistive-technology checks' },
      { id: 'retest', code: 'Fix root causes, retest, and preserve regression coverage' },
    ],
    correctOrder: ['scope', 'render', 'scan', 'triage', 'manual', 'retest'],
    requiredOrderPairs: [
      ['scope', 'render'],
      ['render', 'scan'],
      ['scan', 'triage'],
      ['render', 'manual'],
      ['triage', 'retest'],
      ['manual', 'retest'],
    ],
    explanation:
      'A useful evaluation starts with a defined scope, combines automation with human checks in either order once the target state exists, and ends by verifying fixes and retaining regression coverage.',
    reference: accessibilityEvaluationReference,
  },
  {
    id: 'accessibility-testing.sequence.lighthouse-run',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Order a basic Lighthouse accessibility audit in Chrome DevTools.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'page', code: 'Open the target page and prepare the state to audit' },
      { id: 'devtools', code: 'Open Chrome DevTools' },
      { id: 'panel', code: 'Select the Lighthouse panel' },
      { id: 'category', code: 'Select the Accessibility category and desired options' },
      { id: 'analyze', code: 'Analyze the page' },
      { id: 'review', code: 'Review failed audits and the manual-check guidance' },
    ],
    correctOrder: ['page', 'devtools', 'panel', 'category', 'analyze', 'review'],
    explanation:
      'Lighthouse audits the current page and state. After generating the report, investigate failed automated audits and continue with the listed manual checks.',
    reference: lighthouseReference,
  },
  {
    id: 'accessibility-testing.sequence.wave-review',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Arrange a contextual WAVE browser-extension review.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'state', code: 'Navigate to the rendered page and state to evaluate' },
      { id: 'run', code: 'Run the WAVE browser extension' },
      { id: 'errors', code: 'Inspect red errors on their affected elements' },
      { id: 'alerts', code: 'Evaluate yellow alerts and green features in context' },
      { id: 'structure', code: 'Inspect headings, landmarks, labels, and reading order' },
      { id: 'record', code: 'Record confirmed barriers with evidence and scope' },
    ],
    correctOrder: ['state', 'run', 'errors', 'alerts', 'structure', 'record'],
    requiredOrderPairs: [
      ['state', 'run'],
      ['run', 'errors'],
      ['run', 'alerts'],
      ['run', 'structure'],
      ['errors', 'record'],
      ['alerts', 'record'],
      ['structure', 'record'],
    ],
    explanation:
      'WAVE overlays information on the rendered interface. Errors, alerts, features, and structure may be reviewed in any order before confirmed findings are recorded.',
    reference: waveReference,
  },
  {
    id: 'accessibility-testing.sequence.axe-test',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Order the core steps of an automated axe test for an opened dialog.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'render', code: 'Render the page or component' },
      { id: 'open', code: 'Perform the interaction that opens the dialog' },
      { id: 'stable', code: 'Wait until the dialog state is stable' },
      { id: 'run', code: 'Run axe against the relevant document or container' },
      { id: 'assert', code: 'Assert violations and review incomplete results' },
      { id: 'rerun', code: 'Fix the component and rerun the test' },
    ],
    correctOrder: ['render', 'open', 'stable', 'run', 'assert', 'rerun'],
    explanation:
      'The scan must run after the meaningful state exists and has stabilized. Confirmed violations can fail the test, while incomplete results still need manual review.',
    reference: axeReference,
  },
  {
    id: 'accessibility-testing.sequence.keyboard-flow',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Arrange a keyboard-only smoke test for a page flow.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'start', code: 'Reload the flow and put the pointer aside' },
      { id: 'forward', code: 'Tab forward through every interactive element' },
      { id: 'operate', code: 'Operate controls with their expected keyboard commands' },
      { id: 'reverse', code: 'Use Shift+Tab to verify reverse navigation' },
      { id: 'focus', code: 'Confirm focus remains visible and logically ordered' },
      { id: 'complete', code: 'Complete the task and verify focus after state changes' },
    ],
    correctOrder: ['start', 'forward', 'operate', 'reverse', 'focus', 'complete'],
    requiredOrderPairs: [
      ['start', 'forward'],
      ['forward', 'operate'],
      ['forward', 'reverse'],
      ['forward', 'focus'],
      ['operate', 'complete'],
      ['reverse', 'complete'],
      ['focus', 'complete'],
    ],
    explanation:
      'After establishing forward reachability, operation, reverse navigation, and focus checks may be interleaved before completing the task and verifying state changes.',
    reference: wcagKeyboardTrapReference,
  },
  {
    id: 'accessibility-testing.sequence.dialog-focus',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Put this modal-dialog focus lifecycle in user order.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'trigger', code: 'Keyboard focus reaches the dialog trigger' },
      { id: 'activate', code: 'The user activates the trigger' },
      { id: 'inside', code: 'Focus moves to a suitable element inside the open dialog' },
      { id: 'contain', code: 'Tab navigation remains within the modal while it is open' },
      { id: 'close', code: 'The user closes the dialog with an available keyboard method' },
      { id: 'return', code: 'Focus returns to the trigger or another logical destination' },
    ],
    correctOrder: ['trigger', 'activate', 'inside', 'contain', 'close', 'return'],
    explanation:
      'A modal moves focus inside, contains it only while open, offers a keyboard-accessible close method, and restores focus to a logical point afterward.',
    reference: ariaDialogReference,
  },
  {
    id: 'accessibility-testing.sequence.form-error',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Order a manual test of an accessible form validation error.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'invalid', code: 'Enter invalid data using the keyboard' },
      { id: 'submit', code: 'Submit the form' },
      { id: 'notice', code: 'Verify the error is visible and programmatically announced' },
      {
        id: 'association',
        code: 'Confirm the message identifies and is associated with the field',
      },
      { id: 'correct', code: 'Correct the value and submit again' },
      { id: 'clear', code: 'Verify stale error state and messaging are cleared' },
    ],
    correctOrder: ['invalid', 'submit', 'notice', 'association', 'correct', 'clear'],
    requiredOrderPairs: [
      ['invalid', 'submit'],
      ['submit', 'notice'],
      ['submit', 'association'],
      ['notice', 'correct'],
      ['association', 'correct'],
      ['correct', 'clear'],
    ],
    explanation:
      'After submission, visibility/announcement and field association may be checked in either order before correcting the value and confirming stale errors are removed.',
    reference: accessibilityEvaluationReference,
  },
  {
    id: 'accessibility-testing.sequence.name-finding',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Arrange the investigation of an unnamed control reported by a tool.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'locate', code: 'Locate and reproduce the flagged control in the interface' },
      { id: 'inspect', code: 'Inspect its element, role, and computed accessible name' },
      { id: 'source', code: 'Identify why no meaningful name is exposed' },
      { id: 'fix', code: 'Add or repair the best visible or programmatic label' },
      { id: 'automated', code: 'Rerun the automated rule' },
      { id: 'manual', code: 'Confirm the final name in the rendered accessibility tree' },
    ],
    correctOrder: ['locate', 'inspect', 'source', 'fix', 'automated', 'manual'],
    requiredOrderPairs: [
      ['locate', 'inspect'],
      ['inspect', 'source'],
      ['source', 'fix'],
      ['fix', 'automated'],
      ['fix', 'manual'],
    ],
    explanation:
      'Tool output begins the investigation. Inspect and fix the naming source, then verify with both the automated rule and rendered accessibility information in either order.',
    reference: axeReference,
  },
  {
    id: 'accessibility-testing.sequence.issue-triage',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Order a responsible accessibility issue-triage workflow.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'reproduce', code: 'Reproduce the finding in the affected state' },
      { id: 'guidance', code: 'Read the rule guidance and inspect the related markup' },
      { id: 'impact', code: 'Confirm the barrier and describe its user impact' },
      { id: 'scope', code: 'Find other instances from the same component or pattern' },
      { id: 'repair', code: 'Repair the root component or content source' },
      { id: 'verify', code: 'Verify the fix manually and with regression tests' },
    ],
    correctOrder: ['reproduce', 'guidance', 'impact', 'scope', 'repair', 'verify'],
    requiredOrderPairs: [
      ['reproduce', 'guidance'],
      ['reproduce', 'impact'],
      ['reproduce', 'scope'],
      ['guidance', 'repair'],
      ['impact', 'repair'],
      ['scope', 'repair'],
      ['repair', 'verify'],
    ],
    explanation:
      'After reproduction, guidance, user impact, and pattern scope may be investigated in any order before repairing the source and verifying the result.',
    reference: accessibilityEvaluationReference,
  },
  {
    id: 'accessibility-testing.sequence.delivery-layers',
    topicId: 'accessibility-testing',
    kind: 'sequence',
    prompt: 'Arrange accessibility practices from authoring through release learning.',
    instruction: 'Drag rows, or use the Move up and Move down buttons.',
    items: [
      { id: 'author', code: 'Build with semantic HTML and accessible component contracts' },
      { id: 'component', code: 'Check components with linting, unit tests, and axe' },
      { id: 'flow', code: 'Scan representative browser flows and dynamic states' },
      { id: 'manual', code: 'Perform keyboard, visual, and screen-reader checks' },
      { id: 'users', code: 'Include people with disabilities in evaluation where possible' },
      {
        id: 'monitor',
        code: 'Release, monitor regressions, and feed findings back into components',
      },
    ],
    correctOrder: ['author', 'component', 'flow', 'manual', 'users', 'monitor'],
    requiredOrderPairs: [
      ['author', 'component'],
      ['author', 'manual'],
      ['author', 'users'],
      ['component', 'flow'],
      ['flow', 'monitor'],
      ['manual', 'monitor'],
      ['users', 'monitor'],
    ],
    explanation:
      'Accessibility is most effective as a lifecycle: component and flow checks form a delivery path, while manual and user evaluation can happen alongside it before production learning feeds back into the system.',
    reference: accessibilityEvaluationReference,
  },
] as const satisfies readonly SequenceQuestion[]
